import fs from 'fs';
import { generateBoxArtSvg } from './generator_helpers.js';

function writeConsoleFile(filename, varName, consoleKey, games) {
  const code = `import { VideoGameItem } from '../../types';

export const ${varName}: VideoGameItem[] = ${JSON.stringify(games, null, 2)};
`;
  fs.writeFileSync(filename, code, 'utf-8');
  console.log(`Wrote ${games.length} games to ${filename}`);
}

// -------------------------------------------------------------
// 1. PS1 (100 Games)
// -------------------------------------------------------------
const rawPs1 = [
  ["Metal Gear Solid", "Konami", 1998, ["Stealth", "Azione"], ["Spionaggio Militare", "Guerra Fredda"], "3a Persona", "Tactical Espionage Action. Snake a Shadow Moses.", "PEGI 16", "Metal Gear", "#0f2027", "#203a43", "🐍"],
  ["Final Fantasy VII", "Square", 1997, ["JRPG", "Avventura"], ["Cyberpunk", "Materia", "Ribellione"], "3a Persona", "Cloud Strife, la spada Buster e Sephiroth.", "PEGI 12", "Final Fantasy", "#000428", "#004e92", "🗡️"],
  ["Final Fantasy VIII", "Square", 1999, ["JRPG", "Avventura"], ["Fantascienza", "Amore", "Stregoneria"], "3a Persona", "Squall Leonhart, la Gunblade e il Garden di Balamb.", "PEGI 12", "Final Fantasy", "#141e30", "#243b55", "🦁"],
  ["Final Fantasy IX", "Square", 2000, ["JRPG", "Avventura"], ["High Fantasy", "Teatro", "Magia"], "3a Persona", "Gidan Tribal, Vivi Ornitier e il regno di Alexandria.", "PEGI 12", "Final Fantasy", "#2c3e50", "#3498db", "✨"],
  ["Castlevania: Symphony of the Night", "Konami", 1997, ["Metroidvania", "Azione"], ["Gotico", "Vampiri", "Castello di Dracula"], "2D Side-Scroller", "What is a man? A miserable little pile of secrets! Alucard.", "PEGI 12", "Castlevania", "#1e0c1b", "#8b0000", "🦇"],
  ["Resident Evil", "Capcom", 1996, ["Survival Horror"], ["Zombi", "Villa Spencer", "Biohazard"], "3a Persona", "Il capostipite del survival horror a Villa Spencer.", "PEGI 18", "Resident Evil", "#1a0000", "#800000", "☣️"],
  ["Resident Evil 2", "Capcom", 1998, ["Survival Horror"], ["Zombi", "Raccoon City", "Polizia"], "3a Persona", "Leon S. Kennedy e Claire Redfield a Raccoon City.", "PEGI 18", "Resident Evil", "#200101", "#990000", "🧟"],
  ["Resident Evil 3: Nemesis", "Capcom", 1999, ["Survival Horror"], ["Fuga", "Nemesis", "Raccoon City"], "3a Persona", "STARS! L'implacabile caccia di Nemesis a Jill Valentine.", "PEGI 18", "Resident Evil", "#150000", "#b30000", "⚠️"],
  ["Silent Hill", "Konami", 1999, ["Survival Horror", "Psicologico"], ["Nebbia", "Incubi", "Mondo Rovesciato"], "3a Persona", "Harry Mason cerca disperatamente la figlia Cheryl.", "PEGI 18", "Silent Hill", "#2b2b2b", "#8b0000", "📻"],
  ["Tekken 3", "Namco", 1998, ["Picchiaduro 3D"], ["Arti Marziali", "Torneo del Pugno di Ferro"], "3a Persona", "Jin Kazama, Hwoarang e Eddy Gordo nell'apice del picchiaduro 3D.", "PEGI 12", "Tekken", "#2b0a0a", "#e65100", "🥋"],
  ["Crash Bandicoot", "Naughty Dog", 1996, ["Platform 3D"], ["Frutti Wumpa", "Isole Wumpa", "Scienziati Pazzi"], "3a Persona", "Crash affronta gli scagnozzi del Dr. Neo Cortex.", "PEGI 3", "Crash Bandicoot", "#bf360c", "#ff6d00", "🍎"],
  ["Crash Bandicoot 2: Cortex Strikes Back", "Naughty Dog", 1997, ["Platform 3D"], ["Cristalli del Potere", "Warp Room"], "3a Persona", "Raccogli 25 cristalli per salvare il mondo.", "PEGI 3", "Crash Bandicoot", "#d84315", "#ff9100", "💎"],
  ["Crash Bandicoot: Warped", "Naughty Dog", 1998, ["Platform 3D"], ["Viaggi nel Tempo", "Preistoria", "Medioevo"], "3a Persona", "Viaggi nel tempo con Coco, Aku Aku e la bazooka a mele.", "PEGI 3", "Crash Bandicoot", "#e65100", "#ffa726", "⏳"],
  ["Crash Team Racing (CTR)", "Naughty Dog", 1999, ["Kart Arcade", "Corse"], ["Power Slide", "Nitros Oxide", "Sfide a 4"], "3a Persona", "Gare a derapata folli per salvare la Terra da Nitros Oxide.", "PEGI 3", "Crash Bandicoot", "#ef6c00", "#ffb74d", "🏎️"],
  ["Spyro the Dragon", "Insomniac Games", 1998, ["Platform 3D"], ["Draghi", "Gemme", "Gnasty Gnorc"], "3a Persona", "Il draghetto viola Spyro e la libellula Sparx liberano i draghi.", "PEGI 3", "Spyro", "#4a148c", "#ab47bc", "🐲"],
  ["Spyro 2: Ripto's Rage!", "Insomniac Games", 1999, ["Platform 3D"], ["Mondo di Avalar", "Talismani", "Orbi"], "3a Persona", "Spyro viaggia ad Avalar per sconfiggere il tiranno Ripto.", "PEGI 3", "Spyro", "#6a1b9a", "#ba68c8", "🔮"],
  ["Spyro: Year of the Dragon", "Insomniac Games", 2000, ["Platform 3D"], ["Uova di Drago", "Mondi Dimenticati", "Skateboard"], "3a Persona", "Recupera le 150 uova di drago rubate dalla Maga.", "PEGI 3", "Spyro", "#7b1fa2", "#ce93d8", "🥚"],
  ["Gran Turismo", "Polyphony Digital", 1997, ["Simulazione di Guida", "Corse"], ["The Real Driving Simulator", "Patenti", "Auto Reali"], "3a Persona", "The Real Driving Simulator: fisica rivoluzionaria e centinaia di vetture.", "PEGI 3", "Gran Turismo", "#0d47a1", "#1976d2", "🏁"],
  ["Gran Turismo 2", "Polyphony Digital", 1999, ["Simulazione di Guida", "Corse"], ["Rally", "Oltre 600 Auto", "Due CD"], "3a Persona", "Due dischi leggendari: Arcade Mode e Gran Turismo Simulation.", "PEGI 3", "Gran Turismo", "#1565c0", "#42a5f5", "🏎️"],
  ["Tomb Raider", "Core Design", 1996, ["Azione", "Avventura"], ["Archeologia", "Tombe Antiche", "T-Rex"], "3a Persona", "Lara Croft esplora le rovine del Perù, Grecia, Egitto e Atlantide.", "PEGI 16", "Tomb Raider", "#2e7d32", "#4caf50", "🏺"],
  ["Tomb Raider II", "Core Design", 1997, ["Azione", "Avventura"], ["Pugnale di Xian", "Venezia", "Muraglia Cinese"], "3a Persona", "Alla ricerca del Pugnale di Xian tra i canali di Venezia e il Tibet.", "PEGI 16", "Tomb Raider", "#1b5e20", "#66bb6a", "🗡️"],
  ["Tomb Raider III", "Core Design", 1998, ["Azione", "Avventura"], ["Meteorite", "Area 51", "Giungla Indiana"], "3a Persona", "Quattro frammenti di meteorite sparsi per il globo.", "PEGI 16", "Tomb Raider", "#33691e", "#8bc34a", "🗿"],
  ["Tony Hawk's Pro Skater", "Neversoft", 1999, ["Skateboard Arcade", "Sport"], ["Kickflip", "Warehouse", "Punk Rock"], "3a Persona", "Trick spettacolari, punteggi record e soundtrack punk indimenticabile.", "PEGI 12", "Tony Hawk", "#bf360c", "#ff5722", "🛹"],
  ["Tony Hawk's Pro Skater 2", "Neversoft", 2000, ["Skateboard Arcade", "Sport"], ["Manuals", "Park Editor", "Hangar"], "3a Persona", "Il capolavoro assoluto dello skate con i manual per combo infinite.", "PEGI 12", "Tony Hawk", "#d84315", "#ff7043", "🛹"],
  ["Chrono Cross", "Square", 1999, ["JRPG", "Avventura"], ["Dimensioni Parallele", "Destino", "Oceano"], "3a Persona", "Serge e Kid tra due realtà parallele legate dal passato di Chrono.", "PEGI 12", "Chrono", "#006064", "#00bcd4", "⏳"],
  ["Xenogears", "Square", 1998, ["JRPG", "Mecha"], ["Filosofia", "Religione", "Robot Giganti"], "3a Persona", "Fei Fong Wong, i Gear giganti e un racconto filosofico monumentale.", "PEGI 12", "Xeno", "#311b92", "#673ab7", "🤖"],
  ["Vagrant Story", "Square", 2000, ["Action RPG"], ["Lea Monde", "Riskbreaker", "Gotico Oscuro"], "3a Persona", "Ashley Riot investiga nella città maledetta di Lea Monde.", "PEGI 16", "Ivalice", "#3e2723", "#8d6e63", "⚔️"],
  ["MediEvil", "SCE Cambridge", 1998, ["Action Adventure", "Hack and Slash"], ["Gallowmere", "Zarok", "Umorismo Gotico"], "3a Persona", "Sir Daniel Fortesque risorge per riscattare il proprio onore.", "PEGI 12", "MediEvil", "#263238", "#78909c", "💀"],
  ["MediEvil 2", "SCE Cambridge", 2000, ["Action Adventure"], ["Londra Vittoriana", "Lord Palethorn"], "3a Persona", "Sir Dan torna nella Londra vittoriana a colpi di spada e pistola.", "PEGI 12", "MediEvil", "#37474f", "#90a4ae", "🎩"],
  ["Dino Crisis", "Capcom", 1999, ["Survival Horror"], ["Dinosauri", "Isola Ibis", "Regina"], "3a Persona", "Panic Horror: velociraptor e T-Rex invece degli zombi.", "PEGI 16", "Dino Crisis", "#004d40", "#009688", "🦖"],
  ["Dino Crisis 2", "Capcom", 2000, ["Azione", "Sparatutto"], ["Combo Punti", "Giungla Preistorica"], "3a Persona", "Azione frenetica a colpi di fucile d'assalto tra orde di dinosauri.", "PEGI 16", "Dino Crisis", "#00695c", "#26a69a", "🔫"],
  ["Parasite Eve", "Square", 1998, ["Action RPG", "Horror"], ["Mitocondri", "New York", "Aya Brea"], "3a Persona", "La poliziotta Aya Brea affronta la mutazione mitocondriale a Manhattan.", "PEGI 16", "Parasite Eve", "#880e4f", "#e91e63", "🧬"],
  ["Parasite Eve II", "Square", 1999, ["Action RPG", "Survival Horror"], ["Dryfield", "Neo-Mitochondria"], "3a Persona", "Aya Brea agente MIST investiga nella cittadina desertica di Dryfield.", "PEGI 16", "Parasite Eve", "#ad1457", "#f06292", "🏜️"],
  ["Syphon Filter", "Eidetic", 1999, ["Third-Person Shooter", "Stealth"], ["Gabe Logan", "Taser Elettrico", "Virus"], "3a Persona", "L'agente Gabe Logan sventa la minaccia del letale virus biologico.", "PEGI 16", "Syphon Filter", "#1a237e", "#3f51b5", "⚡"],
  ["Syphon Filter 2", "Eidetic", 2000, ["Third-Person Shooter", "Stealth"], ["Montagne Rocciose", "Lian Xing"], "3a Persona", "Doppio disco di pura azione stealth tra neve e basi segrete.", "PEGI 16", "Syphon Filter", "#283593", "#5c6bc0", "🎯"],
  ["Syphon Filter 3", "Bend Studio", 2001, ["Third-Person Shooter"], ["Processo al Senato", "Missioni Flashback"], "3a Persona", "La conclusione della trilogia originale con rivelazioni scottanti.", "PEGI 16", "Syphon Filter", "#303f9f", "#7986cb", "🎖️"],
  ["Legacy of Kain: Soul Reaver", "Crystal Dynamics", 1999, ["Action Adventure"], ["Nosgoth", "Spettri", "Raziel"], "3a Persona", "Raziel, il Mietitore di Anime, in cerca di vendetta contro Kain.", "PEGI 16", "Legacy of Kain", "#212121", "#00e676", "🗡️"],
  ["Ape Escape", "SCE Japan Studio", 1999, ["Platform 3D"], ["Doppio Analogico", "Scimmie Monelle", "Retino"], "3a Persona", "Il primo gioco ad aver reso obbligatorio il controller DualShock!", "PEGI 3", "Ape Escape", "#ff6f00", "#ffca28", "🐵"],
  ["Twisted Metal 2", "SingleTrac", 1996, ["Combattimento Veicolare"], ["Sweet Tooth", "Calypso", "Torneo Mortale"], "3a Persona", "Il celebre furgoncino dei gelati armato di missili e follia distruttiva.", "PEGI 16", "Twisted Metal", "#b71c1c", "#ff1744", "🤡"],
  ["Driver", "Reflections Interactive", 1999, ["Guida", "Azione"], ["Tanner", "Poliziotto Sotto Copertura", "Inseguimenti"], "3a Persona", "Fughe al cardiopalma a bordo di muscle car americane anni 70.", "PEGI 12", "Driver", "#37474f", "#ffab00", "🚔"],
  ["Driver 2", "Reflections Interactive", 2000, ["Guida", "Open World"], ["Uscire dall'Auto", "Chicago", "L'Avana"], "3a Persona", "Per la prima volta Tanner può scendere dal veicolo e rubarne altri.", "PEGI 12", "Driver", "#263238", "#ffd600", "🚗"],
  ["Wipeout 2097 / XL", "Psygnosis", 1996, ["Corse Antigravità"], ["Formula F500", "Musica Elettronica", "Missili"], "3a Persona", "Corse futuristiche ipersoniche con i brani di Prodigy e Chemical Brothers.", "PEGI 3", "Wipeout", "#004d40", "#00e5ff", "🚀"],
  ["Wipeout 3", "Psygnosis", 1999, ["Corse Antigravità"], ["Design Minimal", "F7200 League"], "3a Persona", "Eleganza visiva curata da The Designers Republic e velocità estrema.", "PEGI 3", "Wipeout", "#006064", "#18ffff", "⚡"],
  ["Suikoden", "Konami", 1995, ["JRPG", "Strategia"], ["108 Stelle del Destino", "Castello Base"], "2D Side-Scroller", "Raduna le 108 Stelle del Destino per rovesciare l'Impero Scarlatto.", "PEGI 12", "Suikoden", "#4e342e", "#8d6e63", "⭐"],
  ["Suikoden II", "Konami", 1998, ["JRPG", "Avventura"], ["Luca Blight", "Runa dell'Inizio", "Amicizia"], "2D Side-Scroller", "Riconosciuto all'unanimità come uno dei più grandi JRPG della storia.", "PEGI 12", "Suikoden", "#3e2723", "#a1887f", "🌟"],
  ["Oddworld: Abe's Oddysee", "Oddworld Inhabitants", 1997, ["Platform Cinematico"], ["Mudokon", "Mattatoi Ernia", "GameSpeak"], "2D Side-Scroller", "Hello. Follow me. Ok! Guida i tuoi compagni verso la libertà.", "PEGI 12", "Oddworld", "#1b5e20", "#4caf50", "👁️"],
  ["Oddworld: Abe's Exoddus", "Oddworld Inhabitants", 1998, ["Platform Cinematico"], ["Tempesta d'Anime", "Necrum", "Possessione"], "2D Side-Scroller", "Abe scopre il macabro ingrediente segreto della birra SoulStorm.", "PEGI 12", "Oddworld", "#2e7d32", "#81c784", "🍺"],
  ["Rayman", "Ubisoft", 1995, ["Platform 2D"], ["Mondo dei Sogni", "Mr. Dark", "Electoons"], "2D Side-Scroller", "Animazioni disegnate a mano e una difficoltà leggendaria senza arti!", "PEGI 3", "Rayman", "#4a148c", "#ba68c8", "🥊"],
  ["Rayman 2: The Great Escape", "Ubisoft", 1999, ["Platform 3D"], ["Pirati Robot", "Radura dei Sogni", "Lums"], "3a Persona", "Il salto perfetto nella terza dimensione con la maschera di Polokus.", "PEGI 3", "Rayman", "#6a1b9a", "#ab47bc", "✨"],
  ["Tenchu: Stealth Assassins", "Acquire", 1998, ["Stealth", "Azione"], ["Ninja", "Rikimaru", "Ayane"], "3a Persona", "Live in shadow, act in secret. Il capostipite del ninja stealth 3D.", "PEGI 16", "Tenchu", "#212121", "#d50000", "🗡️"],
  ["Tenchu 2: Birth of the Stealth Assassins", "Acquire", 2000, ["Stealth", "Azione"], ["Lord Gohda", "Tatsumaru", "Mission Editor"], "3a Persona", "Il prequel che svela le origini dei guerrieri ninja Azuma.", "PEGI 16", "Tenchu", "#263238", "#ff1744", "🌙"],
  ["Colin McRae Rally 2.0", "Codemasters", 2000, ["Rally", "Corse"], ["Ford Focus WRC", "Fango e Neve", "Giappone"], "3a Persona", "Il benchmark assoluto dei giochi di rally su console 32-bit.", "PEGI 3", "Colin McRae", "#01579b", "#03a9f4", "🚗"],
  ["Need for Speed III: Hot Pursuit", "EA Canada", 1998, ["Corse Arcade"], ["Supercar", "Inseguimenti Polizia", "Autostrade"], "3a Persona", "Sfida la polizia o guida l'auto della pattuglia a sirene spiegate!", "PEGI 3", "Need for Speed", "#b71c1c", "#f44336", "🚓"],
  ["Tekken 2", "Namco", 1996, ["Picchiaduro 3D"], ["Kazuya Mishima", "Heihachi", "Jun Kazama"], "3a Persona", "Il torneo che ha consacrato la serie con Kazuya al vertice.", "PEGI 12", "Tekken", "#3e2723", "#d84315", "👊"],
  ["Soul Blade", "Namco", 1996, ["Picchiaduro con Armi"], ["Soul Edge", "Siegfried", "Cervantes"], "3a Persona", "The legend will never die! La spettacolare intro CGI con 'The Edge of Soul'.", "PEGI 12", "Soulcalibur", "#004d40", "#00bfa5", "⚔️"],
  ["Rival Schools: United by Fate", "Capcom", 1998, ["Picchiaduro 3D"], ["Liceali Giapponesi", "Team Attack", "Batsu"], "3a Persona", "Studenti e professori si affrontano a colpi di arti marziali e libri.", "PEGI 12", "Capcom Fighters", "#e65100", "#ff9800", "🏫"],
  ["Street Fighter Alpha 3", "Capcom", 1998, ["Picchiaduro 2D"], ["ISM System", "World Tour", "Ryu e Akuma"], "2D Side-Scroller", "Beat 'em up, guys! Il picchiaduro 2D definitivo dell'era a 32-bit.", "PEGI 12", "Street Fighter", "#bf360c", "#ff5722", "🥋"],
  ["Mega Man X4", "Capcom", 1997, ["Platform Action"], ["Zero Spadaccino", "Reploid", "Sigma"], "2D Side-Scroller", "Scegli se giocare con Mega Man X o con la sciabola laser di Zero.", "PEGI 7", "Mega Man", "#01579b", "#29b6f6", "🤖"],
  ["Mega Man Legends", "Capcom", 1997, ["Action Adventure 3D"], ["Mega Man Volnutt", "Kattelox Island", "Bonne Family"], "3a Persona", "L'iconico Blue Bomber reinventato in una vivace avventura 3D ad anime.", "PEGI 7", "Mega Man", "#0277bd", "#4fc3f7", "⚙️"],
  ["Final Fantasy Tactics", "Square", 1997, ["GDR Tattico"], ["Ivalice", "Ramza Beoulve", "Guerra dei Leoni"], "Isometrica", "Intrighi politici, classi di combattimento e strategia pura.", "PEGI 12", "Final Fantasy", "#37474f", "#90a4ae", "♟️"],
  ["Valkyrie Profile", "tri-Ace", 1999, ["JRPG", "Mitologia Norrena"], ["Lenneth", "Einherjar", "Ragnarok"], "2D Side-Scroller", "Lenneth la Valchiria sceglie gli eroi caduti per il Valhalla.", "PEGI 12", "Valkyrie", "#1a237e", "#3949ab", "🪽"],
  ["Grandia", "Game Arts", 1997, ["JRPG", "Avventura"], ["Justin e Feena", "Mondo Ignoto", "Spiriti"], "3a Persona", "Un inno all'avventura giovanile e alla scoperta di civiltà perdute.", "PEGI 12", "Grandia", "#004d40", "#00897b", "🧭"],
  ["Star Ocean: The Second Story", "tri-Ace", 1998, ["Action RPG"], ["Claude e Rena", "Pianeta Expel", "Crafting"], "3a Persona", "Doppio protagonista, combattimenti in tempo reale e 86 finali diversi!", "PEGI 12", "Star Ocean", "#0d47a1", "#1e88e5", "🌌"],
  ["Breath of Fire III", "Capcom", 1997, ["JRPG", "Avventura"], ["Ryu Drago", "Geni Draconici", "Teepo"], "Isometrica", "Cresci dall'infanzia all'età adulta padroneggiando il potere dei draghi.", "PEGI 12", "Breath of Fire", "#e65100", "#fb8c00", "🐲"],
  ["Breath of Fire IV", "Capcom", 2000, ["JRPG", "Avventura"], ["Fou-Lu", "Impero Fou", "Draghi Divini"], "Isometrica", "La narrazione intrecciata tra il giovane Ryu e il risvegliato dio Fou-Lu.", "PEGI 12", "Breath of Fire", "#d84315", "#f4511e", "⚡"],
  ["Legend of Mana", "Square", 1999, ["Action RPG"], ["Albero di Mana", "Land Creation", "Arte Dipinta"], "Isometrica", "Ricostruisci il mondo di Fa'Diel piazzando manufatti magici sulla mappa.", "PEGI 12", "Mana", "#1b5e20", "#43a047", "🌳"],
  ["Alundra", "Matrix Software", 1997, ["Action Adventure", "Enigmi"], ["Inaros", "Camminatore di Sogni", "Villaggio"], "Isometrica", "Spesso definito lo 'Zelda maturo' di casa PlayStation, ricco di enigmi.", "PEGI 12", "Alundra", "#33691e", "#689f38", "💤"],
  ["Klonoa: Door to Phantomile", "Namco", 1997, ["Platform 2.5D"], ["Phantomile", "Anello del Vento", "Wahoo"], "2D Side-Scroller", "Un viaggio poetico tra sogni e ricordi con il simpatico Klonoa.", "PEGI 3", "Klonoa", "#006064", "#00acc1", "🎈"],
  ["Ridge Racer Type 4 (R4)", "Namco", 1998, ["Corse Arcade"], ["Reiko Nagase", "Drift Perfetto", "Grand Prix"], "3a Persona", "L'apice dello stile arcade anni 90 con colonna sonora acid jazz.", "PEGI 3", "Ridge Racer", "#e53935", "#ff5252", "🏎️"],
  ["Destruction Derby 2", "Reflections", 1996, ["Demolition Derby", "Corse"], ["The Bowl", "Carambole", "Lamiere Contorte"], "3a Persona", "Distruggi le carrozzerie degli avversari in arene senza via di fuga!", "PEGI 12", "Destruction Derby", "#212121", "#ff9800", "💥"],
  ["Ace Combat 2", "Namco", 1997, ["Simulazione Volo Arcade"], ["Scarface Squadron", "Caccia Militari"], "3a Persona", "Duelli aerei mozzafiato a bordo dei più potenti jet da combattimento.", "PEGI 12", "Ace Combat", "#0d47a1", "#2196f3", "✈️"],
  ["Ace Combat 3: Electrosphere", "Namco", 1999, ["Simulazione Volo", "Sci-Fi"], ["Cyberpunk 2040", "Megacorporazioni", "Anime"], "3a Persona", "Guerra aerea nel futuro con bivi narrativi e finali multipli.", "PEGI 12", "Ace Combat", "#1a237e", "#3d5afe", "🛰️"],
  ["Blood Omen: Legacy of Kain", "Silicon Knights", 1996, ["Action RPG"], ["Kain Vampiro", "Pillastri di Nosgoth"], "Isometrica", "Vae Victis! L'ascesa al potere del nobile Kain tramutato in vampiro.", "PEGI 18", "Legacy of Kain", "#212121", "#b71c1c", "🩸"],
  ["Fear Effect", "Kronos Digital", 2000, ["Survival Horror", "Azione"], ["Hana Tsu-Vachel", "Cel-Shading", "Inferno Cinese"], "3a Persona", "Atmosfere cyberpunk, cel-shading pionieristico e terrore mitologico.", "PEGI 18", "Fear Effect", "#311b92", "#7c4dff", "🔥"],
  ["Fear Effect 2: Retro Helix", "Kronos Digital", 2001, ["Survival Horror"], ["Prequel", "DNA Mutation", "Rain Qin"], "3a Persona", "Intrighi internazionali e orrori genetici tra Hong Kong e New York.", "PEGI 18", "Fear Effect", "#4a148c", "#8e24aa", "🧬"],
  ["Tomba! (Tombi!)", "Whoopee Camp", 1997, ["Platform Adventure"], ["Maiali Malvagi", "Zaino Morso", "Eventi"], "2D Side-Scroller", "Il ragazzo selvaggio dai capelli rosa a caccia di sacchi maiale!", "PEGI 3", "Tomba", "#e91e63", "#ff4081", "🐷"],
  ["Tomba! 2: The Evil Swine Return", "Whoopee Camp", 1999, ["Platform Adventure 3D"], ["Costumi Speciali", "Tabby Rapita"], "3a Persona", "Tombi torna con poteri elementali e un mondo interamente 3D.", "PEGI 3", "Tomba", "#c2185b", "#ec407a", "🐗"],
  ["Front Mission 3", "Square", 1999, ["GDR Tattico", "Mecha"], ["Wanzer", "Kazuki Takemura", "Doppio Scenario"], "Isometrica", "Guerra tra superpotenze a bordo di imponenti robot Wanzer personalizzabili.", "PEGI 12", "Front Mission", "#263238", "#607d8b", "🤖"],
  ["Wild Arms", "Media.Vision", 1996, ["JRPG", "Western Fantasy"], ["Filgaia", "Rudy, Jack e Cecilia", "ARM"], "3a Persona", "L'indimenticabile fischiettio western dell'intro nel mondo di Filgaia.", "PEGI 12", "Wild Arms", "#bf360c", "#ff7043", "🤠"],
  ["Wild Arms 2", "Media.Vision", 1999, ["JRPG"], ["Squadra ARMS", "Minaccia Odessa"], "3a Persona", "Tre eroi reclutati in una task force segreta per proteggere Filgaia.", "PEGI 12", "Wild Arms", "#e64a19", "#ff8a65", "🔫"],
  ["Lunar: Silver Star Story Complete", "Game Arts", 1998, ["JRPG"], ["Alex e Luna", "Quattro Draghi", "Anime Cutscenes"], "2D Side-Scroller", "Una fiaba classica ricca di animazioni cantate e dialoghi memorabili.", "PEGI 12", "Lunar", "#1565c0", "#42a5f5", "🌙"],
  ["Lunar 2: Eternal Blue Complete", "Game Arts", 1999, ["JRPG"], ["Hiro e Lucia", "Dea Althena"], "2D Side-Scroller", "Mille anni dopo il primo capitolo, un viaggio per salvare il mondo blu.", "PEGI 12", "Lunar", "#0d47a1", "#1976d2", "💙"],
  ["Spider-Man", "Neversoft", 2000, ["Action Adventure"], ["Peter Parker", "Venom", "Stan Lee Narratore"], "3a Persona", "L'arrampicamuri definitivo su PS1 con la voce originale di Stan Lee.", "PEGI 12", "Spider-Man", "#b71c1c", "#0d47a1", "🕷️"],
  ["Gex: Enter the Gecko", "Crystal Dynamics", 1998, ["Platform 3D"], ["Parodie TV", "Rez", "Telecomandi"], "3a Persona", "Il geco sarcastico amante della TV trappolato nella Media Dimension.", "PEGI 12", "Gex", "#2e7d32", "#7cb342", "🦎"],
  ["Croc: Legend of the Gobbos", "Argonaut Games", 1997, ["Platform 3D"], ["Coccodrillo Croc", "Gobbos", "Baron Dante"], "3a Persona", "Un piccolo coccodrillo dal cuore d'oro salta per liberare i Gobbos pelosi.", "PEGI 3", "Croc", "#388e3c", "#81c784", "🐊"],
  ["Theme Hospital", "Bullfrog Productions", 1997, ["Simulazione Gestionale"], ["Testa Gonfia", "Invisibilità", "Dottori"], "Isometrica", "Gestisci il tuo ospedale curando le malattie più strampalate e comiche.", "PEGI 12", "Theme Hospital", "#00838f", "#00bcd4", "🏥"],
  ["Rollcage Stage II", "Attention to Detail", 2000, ["Corse Estreme"], ["Auto a Doppia Faccia", "Muri e Soffitti"], "3a Persona", "Bolidi che sfrecciano a 500 km/h su muri e soffitti armati di missili.", "PEGI 7", "Rollcage", "#d84315", "#ff5722", "🏎️"],
  ["Apocalypse", "Neversoft", 1998, ["Third-Person Shooter"], ["Bruce Willis", "Quattro Cavalieri", "Laser"], "3a Persona", "Bruce Willis presta volto e voce a Trey Kincaid contro l'Apocalisse.", "PEGI 16", "Apocalypse", "#212121", "#f44336", "💥"],
  ["Nightmare Creatures", "Kalisto", 1997, ["Survival Horror", "Hack and Slash"], ["Londra 1834", "Adam Crowley", "Virus"], "3a Persona", "Mostri grotteschi per le strade buie di Londra da affrontare a colpi d'ascia.", "PEGI 18", "Nightmare Creatures", "#1a237e", "#b71c1c", "🧟"],
  ["Fighting Force", "Core Design", 1997, ["Picchiaduro a Scorrimento 3D"], ["Hawk e Mace", "Dr. Zeng", "Oggetti Contundenti"], "3a Persona", "Rissa urbana in 3D: raccogli pneumatici, bottiglie e armi da fuoco.", "PEGI 16", "Fighting Force", "#424242", "#e53935", "🥊"],
  ["Parasol Stars", "Taito", 1991, ["Platform Arcade"], ["Bub e Bob Umani", "Ombrello Magico"], "2D Side-Scroller", "Cattura gocce d'acqua e stelle con il magico ombrello colorato.", "PEGI 3", "Bubble Bobble", "#fbc02d", "#ffeb3b", "☂️"],
  ["Kula World", "Game Design Sweden", 1998, ["Rompicapo 3D"], ["Palla da Spiaggia", "Gravità Variabile", "Monete"], "3a Persona", "Fai rotolare la palla gonfiabile sfidando la gravità su piattaforme sospese.", "PEGI 3", "Kula World", "#0288d1", "#4fc3f7", "⚽"],
  ["PaRappa the Rapper", "NanaOn-Sha", 1996, ["Rhythm Game"], ["Kick Punch Chop", "I Gotta Believe!", "Carta"], "2D Side-Scroller", "Kick! Punch! It's all in the mind! Il cane rapper più famoso dei videogiochi.", "PEGI 3", "PaRappa", "#f57c00", "#ffb74d", "🎤"],
  ["Um Jammer Lammy", "NanaOn-Sha", 1999, ["Rhythm Game"], ["Chitarra Elettrica", "MilkCan", "Rock"], "2D Side-Scroller", "Lammy l'agnellina rockeggia con la chitarra per arrivare al concerto.", "PEGI 3", "PaRappa", "#d81b60", "#f06292", "🎸"],
  ["V-Rally 2", "Eden Studios", 1999, ["Rally", "Corse"], ["Track Editor", "Super 1600", "WRC"], "3a Persona", "Oltre 80 tracciati e un editor per creare la propria pista da rally.", "PEGI 3", "V-Rally", "#c2185b", "#e91e63", "🏁"],
  ["FIFA 98: Road to World Cup", "EA Sports", 1997, ["Calcio", "Sport"], ["Song 2 Blur", "Indoor Soccer", "Tutte le Nazionali"], "Isometrica", "La leggendaria intro con 'Song 2' dei Blur e le partite nel palazzetto indoor!", "PEGI 3", "FIFA", "#1b5e20", "#4caf50", "⚽"],
  ["ISS Pro Evolution 2", "Konami Computer Ent. Tokyo", 2000, ["Calcio", "Simulazione"], ["Master League", "Fisica della Palla"], "Isometrica", "La consacrazione definitiva del calcio simulativo secondo Konami.", "PEGI 3", "PES", "#0d47a1", "#1976d2", "🏆"],
  ["WWF SmackDown! 2: Know Your Role", "Yuke's", 2000, ["Wrestling", "Picchiaduro"], ["The Rock", "Stone Cold", "Season Mode"], "3a Persona", "If ya smell what The Rock is cookin'! L'era Attitude al suo massimo splendore.", "PEGI 12", "WWE", "#212121", "#e65100", "🤼"],
  ["Heart of Darkness", "Amazing Studio", 1998, ["Platform Cinematico"], ["Andy e Whisky", "Ombre Oscure", "Orchestra"], "2D Side-Scroller", "Sei anni di sviluppo per un'avventura cinematografica con colonna sonora orchestrale.", "PEGI 12", "Heart of Darkness", "#1a0033", "#ff0055", "🌌"]
];

const ps1Games = rawPs1.map(([title, dev, year, genres, themes, perspective, quote, pegi, franchise, bg, accent, icon], idx) => ({
  id: `ps1-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}`,
  title,
  developer: dev,
  releaseYear: year,
  genres,
  themes,
  perspective,
  mainPlatform: 'PlayStation',
  platforms: ['PS1'],
  iconicQuote: quote,
  coverUrl: generateBoxArtSvg({
    title,
    consoleKey: 'PS1',
    developer: dev,
    year,
    genre: genres[0],
    pegi,
    themeBg: bg,
    accentColor: accent,
    iconSymbol: icon
  }),
  pegi,
  gameModes: ['Giocatore singolo'],
  franchise
}));

writeConsoleFile('src/data/consoles/ps1Games.ts', 'PS1_GAMES', 'PS1', ps1Games);
