import fs from 'fs';
import { generateBoxArtSvg } from './generator_helpers.js';

function writeConsoleFile(filename, varName, games) {
  const code = `import { VideoGameItem } from '../../types';

export const ${varName}: VideoGameItem[] = ${JSON.stringify(games, null, 2)};
`;
  fs.writeFileSync(filename, code, 'utf-8');
  console.log(`Wrote ${games.length} games to ${filename}`);
}

function mapGames(rawList, consoleKey, mainPlatform = 'Xbox') {
  return rawList.map(([title, dev, year, genres, themes, perspective, quote, pegi, franchise, bg, accent, icon]) => ({
    id: `${consoleKey.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}`,
    title,
    developer: dev,
    releaseYear: year,
    genres,
    themes,
    perspective,
    mainPlatform,
    platforms: [consoleKey],
    iconicQuote: quote,
    coverUrl: generateBoxArtSvg({
      title,
      consoleKey,
      developer: dev,
      year,
      genre: genres[0],
      pegi,
      themeBg: bg,
      accentColor: accent,
      iconSymbol: icon
    }),
    pegi,
    gameModes: ['Giocatore singolo'],
    franchise
  }));
}

// Load original 50 games from scripts/generate_xbox.js
const origScript = fs.readFileSync('scripts/generate_xbox.js', 'utf8');
const origMatch = origScript.match(/const rawXboxOrig = (\[[\s\S]*?\n\];)/);
const rawXboxOrig = eval(origMatch[1]);

// -------------------------------------------------------------
// Xbox One (100 Iconic Masterpieces)
// -------------------------------------------------------------
const rawXboxOne = [
  ["Halo 5: Guardians", "343 Industries", 2015, ["First-Person Shooter"], ["Master Chief", "Spartan Locke", "Warzone 60 FPS"], "1a Persona", "La caccia a Master Chief tra i fuochi di Warzone a 60 frame al secondo granitici.", "PEGI 16", "Halo", "#0c1d2e", "#00d2ff", "🪐"],
  ["Halo: The Master Chief Collection", "343 Industries", 2014, ["First-Person Shooter"], ["Halo 1-4", "Remaster Halo 2 Anniversary", "Multiplayer Unico"], "1a Persona", "La collezione definitiva che racchiude l'intera saga di Master Chief in alta definizione.", "PEGI 16", "Halo", "#0a192f", "#4caf50", "🛡️"],
  ["Halo Wars 2", "Creative Assembly", 2017, ["Strategia in Tempo Reale"], ["Atriox", "I Reietti", "Cinematiche Blur"], "Isometrica", "Il temibile brute Atriox guida i Reietti in una delle campagne più spettacolari dell'universo Halo.", "PEGI 16", "Halo", "#21102b", "#d50000", "⚔️"],
  ["Gears of War 4", "The Coalition", 2016, ["Third-Person Shooter"], ["JD Fenix", "Lo Sciame", "Nuova Generazione"], "3a Persona", "JD, Kait e Del affrontano la nuova minaccia dello Sciame con tempeste d'aria devastanti.", "PEGI 18", "Gears of War", "#1a1a1a", "#e53935", "⚙️"],
  ["Gears 5", "The Coalition", 2019, ["Third-Person Shooter"], ["Kait Diaz", "Origini Locuste", "Slitta a Vela"], "3a Persona", "Kait cerca la verità sul proprio lignaggio tra i ghiacci e i deserti rossi sul Skiff.", "PEGI 18", "Gears of War", "#0d1b2a", "#ff1744", "🪓"],
  ["Gears Tactics", "Splash Damage", 2020, ["Strategia a Turni"], ["Gabe Diaz", "Ukkon", "Personalizzazione Unità"], "Isometrica", "Tattica a turni frenetica e brutale nell'epoca dell'Emersione sul pianeta Sera.", "PEGI 18", "Gears of War", "#261c14", "#ff9800", "🎯"],
  ["Gears of War: Ultimate Edition", "The Coalition", 2015, ["Third-Person Shooter"], ["Remake Primo Capitolo", "1080p 60 FPS"], "3a Persona", "Il capostipite della serie ricostruito da zero con animazioni ed effetti moderni.", "PEGI 18", "Gears of War", "#121212", "#c62828", "⛓️"],
  ["Forza Horizon 2", "Playground Games", 2014, ["Corse Open World"], ["Costa Azzurra", "Toscana e Provenza", "Meteo Dinamico"], "3a Persona", "Sfreccia tra i vigneti toscani e le scogliere della Costa Azzurra al tramonto.", "PEGI 3", "Forza Horizon", "#bf360c", "#ffca28", "🏎️"],
  ["Forza Horizon 3", "Playground Games", 2016, ["Corse Open World"], ["Australia Outback", "Foreste Pluviali", "Canguri e Onde"], "3a Persona", "Tu sei il boss del festival: domina le spiagge e il deserto selvaggio dell'Australia.", "PEGI 3", "Forza Horizon", "#ff6f00", "#00e5ff", "🦘"],
  ["Forza Horizon 4", "Playground Games", 2018, ["Corse Open World"], ["Gran Bretagna", "Quattro Stagioni Dinamiche", "Edimburgo"], "3a Persona", "Il mondo cambia ogni settimana tra laghi ghiacciati d'inverno e campi fioriti di primavera.", "PEGI 3", "Forza Horizon", "#1a237e", "#ffab00", "🍁"],
  ["Forza Motorsport 5", "Turn 10 Studios", 2013, ["Simulazione di Guida"], ["Lancio Xbox One", "Drivatar Cloud", "Trigger con Vibrazione d'Impatto"], "1a Persona", "Il debutto dell'IA Drivatar basata sulle abitudini reali dei piloti di tutto il pianeta.", "PEGI 3", "Forza", "#212121", "#e53935", "🏁"],
  ["Forza Motorsport 6", "Turn 10 Studios", 2015, ["Simulazione di Guida"], ["Pioggia e Pozzanghere 3D", "Gare Notturne", "Ford GT"], "1a Persona", "Fisica rivoluzionaria dell'aquaplaning che fa scivolare la vettura su pozzanghere realistiche.", "PEGI 3", "Forza", "#0d47a1", "#29b6f6", "🌧️"],
  ["Forza Motorsport 7", "Turn 10 Studios", 2017, ["Simulazione di Guida"], ["Meteo Dinamico Completo", "Porsche 911 GT2 RS", "4K 60FPS"], "1a Persona", "Oltre 700 bolidi riprodotti fino al minimo bullone da guidare sotto violenti temporali.", "PEGI 3", "Forza", "#1a1a1a", "#ffd600", "🏆"],
  ["Sunset Overdrive", "Insomniac Games", 2014, ["Action Open World"], ["OverCharge Delirium XT", "Grind sui Cavi", "Umorismo Folle"], "3a Persona", "Scivola sui cavi dell'alta tensione sparando fuochi d'artificio e orsetti imbottiti di dinamite!", "PEGI 16", "Sunset Overdrive", "#e65100", "#ffeb3b", "🥤"],
  ["Quantum Break", "Remedy Entertainment", 2016, ["Action Sci-Fi", "Manipolazione Temporale"], ["Jack Joyce", "Frattura del Tempo", "Serie TV Live Action"], "3a Persona", "Blocca il tempo, crea scudi temporali e vivi un thriller fantascientifico d'autore.", "PEGI 16", "Remedy", "#004d40", "#00e5ff", "⏳"],
  ["Ori and the Blind Forest", "Moon Studios", 2015, ["Metroidvania", "Poetico"], ["Foresta di Nibel", "Kuro", "Musica da Brividi"], "2D Side-Scroller", "Un viaggio artistico ed emotivo indimenticabile attraverso una foresta magica morente.", "PEGI 7", "Ori", "#00241b", "#76ff03", "✨"],
  ["Ori and the Will of the Wisps", "Moon Studios", 2020, ["Metroidvania", "Azione"], ["Combattimento Dinamico", "Ku la Civetta", "Arte Visiva Sublime"], "2D Side-Scroller", "Combattimenti frenetici, inseguimenti al cardiopalma e una delle colonne sonore più belle di sempre.", "PEGI 7", "Ori", "#0d1b2a", "#00e5ff", "🦉"],
  ["Sea of Thieves", "Rare", 2018, ["Avventura Pirati Multigiocatore"], ["Velieri e Ciurme", "Kraken", "Onde Oceaniche Prodigiose"], "1a Persona", "Salpa con la tua ciurma, suona la ghironda, scova forzieri e affronta mostri marini leggendari.", "PEGI 12", "Sea of Thieves", "#00363a", "#64ffda", "🏴‍☠️"],
  ["Cuphead", "Studio MDHR", 2017, ["Run and Gun", "Animazione Anni 30"], ["Cartoni Vintage Disegnati a Mano", "Boss Fight Epiche"], "2D Side-Scroller", "Ogni singolo fotogramma è disegnato e inchiostrato a mano nello stile dei cartoon anni Trenta.", "PEGI 7", "Cuphead", "#3e2723", "#ffb300", "☕"],
  ["Titanfall", "Respawn Entertainment", 2014, ["First-Person Shooter"], ["Piloti e Titan", "Wall Run", "Server Cloud Azure"], "1a Persona", "Corsa sui muri a perdifiato prima di chiamare dal cielo un colossale robot d'assalto Titan.", "PEGI 16", "Titanfall", "#102027", "#ff9100", "🤖"],
  ["Titanfall 2", "Respawn Entertainment", 2016, ["First-Person Shooter"], ["Cooper e BT-7274", "Protocollo 3", "Effetto e Causa"], "1a Persona", "Protocollo 3: proteggere il pilota. Uno dei single player più geniali ed emozionanti della storia.", "PEGI 16", "Titanfall", "#0d1b2a", "#29b6f6", "🦾"],
  ["Ryse: Son of Rome", "Crytek", 2013, ["Azione Hack and Slash"], ["Marius Titus", "Impero Romano", "Grafica da Film"], "3a Persona", "La potenza grafica del CryEngine ci proietta tra le legioni romane e i barbari della Britannia.", "PEGI 18", "Ryse", "#3e0000", "#ffb300", "🏛️"],
  ["Dead Rising 3", "Capcom Vancouver", 2013, ["Azione Zombie Open World"], ["Nick Ramos", "Migliaia di Zombie a Schermo", "Armi Combinate"], "3a Persona", "Migliaia di non-morti simultanei travolti da rulli compressori lanciafiamme e spade laser improvvisate.", "PEGI 18", "Dead Rising", "#1b3a1b", "#ff9800", "🧟"],
  ["Dead Rising 4", "Capcom Vancouver", 2016, ["Azione Zombie"], ["Frank West Ritorna", "Natale a Willamette", "Esoscheletri"], "3a Persona", "Frank West torna nel centro commerciale di Willamette per una carneficina a tema natalizio.", "PEGI 18", "Dead Rising", "#2b0000", "#e53935", "📸"],
  ["State of Decay: Year-One Survival Edition", "Undead Labs", 2015, ["Sopravvivenza Zombie"], ["Gestione Comunità", "Costruzione Base", "Morte Permanente"], "3a Persona", "Ogni sopravvissuto conta davvero: se muore in missione non tornerà mai più.", "PEGI 18", "State of Decay", "#1c2518", "#8bc34a", "🏚️"],
  ["State of Decay 2", "Undead Labs", 2018, ["Sopravvivenza Zombie Co-op"], ["Cuori della Peste", "Cooperativa a 4", "Coltivazioni e Risorse"], "3a Persona", "Fonda colonie con gli amici e purifica la contea dai sanguinari Cuori della Peste.", "PEGI 18", "State of Decay", "#1e3a1e", "#c62828", "🩸"],
  ["Killer Instinct (Xbox One)", "Double Helix / Iron Galaxy", 2013, ["Picchiaduro"], ["Jago e Glacius", "Netcode Rollback Perfetto", "Ultra Combo"], "2D Side-Scroller", "Il ritorno del re delle combo con un netcode online che ha fatto scuola a tutta l'industria.", "PEGI 16", "Killer Instinct", "#212121", "#ff1744", "🔥"],
  ["Rare Replay", "Rare", 2015, ["Collezione Classici"], ["30 Giochi Rare", "Banjo Battletoads Conker", "Storia del Videogioco"], "3a Persona", "Trenta capolavori senza tempo festeggiano i trent'anni di Rare in un unico leggendario disco.", "PEGI 18", "Rare", "#1a237e", "#ffd700", "📼"],
  ["ReCore", "Comcept / Armature", 2016, ["Action Platformer"], ["Joule Adams", "Nuclei Robotici Mack e Seth", "Far Eden"], "3a Persona", "Esplora le dune sabbiose di Far Eden insieme a fedeli compagni robotici mutaforma.", "PEGI 12", "ReCore", "#3e2723", "#00e5ff", "🤖"],
  ["Crackdown 3", "Sumo Digital", 2019, ["Action Open World"], ["Terry Crews Agente", "Salto sui Tetti", "Superpoteri"], "3a Persona", "Terry Crews salta tra i grattacieli e scaglia camion contro i boss della dittatura di New Providence.", "PEGI 18", "Crackdown", "#004d40", "#76ff03", "💥"],
  ["D4: Dark Dreams Don't Die", "Access Games", 2014, ["Avventura Investigativa"], ["David Young", "Viaggi Temporali", "Swery65"], "3a Persona", "L'investigatore David Young torna indietro nel tempo toccando oggetti per salvare sua moglie Peggy.", "PEGI 18", "D4", "#261c14", "#e91e63", "🕰️"],
  ["Bleeding Edge", "Ninja Theory", 2020, ["Brawler a Squadre"], ["Cyberpunk 4v4", "Personaggi Bizzarri", "Azione Corpo a Corpo"], "3a Persona", "Scontri corpo a corpo frenetici e stilosi tra emarginati cibernetici potenziati.", "PEGI 16", "Bleeding Edge", "#21102b", "#00e5ff", "🎸"],
  ["The Witcher 3: Wild Hunt (Xbox One X Enhanced)", "CD Projekt RED", 2015, ["Action RPG"], ["Geralt di Rivia", "Ciri e Yennefer", "Novigrad e Skellige"], "3a Persona", "La ricerca della ragazza dai capelli di cenere attraverso un continente dilaniato dalla guerra.", "PEGI 18", "The Witcher", "#1b263b", "#ff9800", "🐺"],
  ["Red Dead Redemption 2 (Xbox One X)", "Rockstar Games", 2018, ["Open World Western"], ["Arthur Morgan", "Banda Van der Linde", "4K Nativo Spettacolare"], "3a Persona", "Arthur Morgan cavalca al tramonto nella rappresentazione più viva e dettagliata mai creata.", "PEGI 18", "Red Dead", "#3e1b00", "#ff3d00", "🤠"],
  ["Grand Theft Auto V (Xbox One)", "Rockstar North", 2014, ["Azione Open World"], ["Visuale in Prima Persona", "Michael Franklin Trevor"], "1a Persona", "Il debutto rivoluzionario della visuale in prima persona per le strade di Los Santos.", "PEGI 18", "Grand Theft Auto", "#0a2612", "#00e676", "💰"],
  ["Metal Gear Solid V: The Phantom Pain", "Kojima Productions", 2015, ["Stealth Open World"], ["Venom Snake", "Mother Base", "Volpe a Due Code"], "3a Persona", "Libertà tattica totale tra le valli afgane e la savana africana ai comandi di Venom Snake.", "PEGI 18", "Metal Gear", "#263238", "#ff5722", "🦊"],
  ["Dark Souls III (Xbox One)", "FromSoftware", 2016, ["Action RPG"], ["Lothric", "Signori dei Tizzoni", "Il Fuoco Svanisce"], "3a Persona", "Le ceneri cercano i tizzoni: affronta i Signori caduti per decidere il destino della fiamma.", "PEGI 16", "Dark Souls", "#1a0005", "#ff6f00", "🔥"],
  ["Sekiro: Shadows Die Twice", "FromSoftware", 2019, ["Action Adventure"], ["Lupo con Braccio Meccanico", "Deflessione Perfetta", "Giappone Sengoku"], "3a Persona", "La lama del Lupo devia ogni fendente a suon di scintille nell'epica era Sengoku.", "PEGI 18", "Sekiro", "#1a0000", "#ff3d00", "🗡️"],
  ["Monster Hunter: World", "Capcom", 2018, ["Action RPG"], ["Nuovo Mondo", "Nergigante", "Ecosistema Vivo"], "3a Persona", "Traccia mostri colossali seguendo gli insetti guida in una giungla che vive e respira.", "PEGI 16", "Monster Hunter", "#1b3a1b", "#ffd600", "🦖"],
  ["Resident Evil 2 (Remake Xbox One)", "Capcom", 2019, ["Survival Horror"], ["Leon e Claire", "Stazione RPD", "Mr. X Inarrestabile"], "3a Persona", "I passi pesanti del trench di Mr. X rimbombano nei corridoi bui della centrale di polizia.", "PEGI 18", "Resident Evil", "#1a0000", "#ff1744", "🧟"],
  ["Resident Evil 7: Biohazard", "Capcom", 2017, ["Survival Horror"], ["Ethan Winters", "Famiglia Baker", "Prima Persona Terribile"], "1a Persona", "Benvenuto in famiglia, figliolo. Il terrore claustrofobico nella palude della Louisiana.", "PEGI 18", "Resident Evil", "#1c2518", "#ff9800", "🏚️"],
  ["Devil May Cry 5", "Capcom", 2019, ["Hack and Slash"], ["Nero Dante V", "Bang Bang Bang Pull My Devil Trigger"], "3a Persona", "Sinfonia di spadate, proiettili e stile tripla S a ritmo di industrial metal travolgente.", "PEGI 18", "Devil May Cry", "#002171", "#ff1744", "⚔️"],
  ["NieR: Automata - BECOME AS GODS Edition", "PlatinumGames", 2018, ["Action RPG"], ["2B e 9S", "Glory to Mankind", "Filosofia e Proiettili"], "3a Persona", "Gli androidi 2B e 9S combattono per un'umanità scomparsa interrogandosi sull'esistenza.", "PEGI 18", "NieR", "#212121", "#bdbdbd", "🤖"],
  ["Final Fantasy XV (Xbox One)", "Square Enix", 2016, ["Action RPG"], ["Noctis e gli Amici", "Regalia sulla Strada", "Stand by Me"], "3a Persona", "Un viaggio on the road a quattro ruote tra amicizia fraterna e un destino imperiale ineluttabile.", "PEGI 16", "Final Fantasy", "#0d1b2a", "#80d8ff", "👑"],
  ["Dragon Ball FighterZ", "Arc System Works", 2018, ["Picchiaduro 2.5D"], ["Goku e Vegeta", "Grafica Fedelissima all'Anime", "3v3"], "2D Side-Scroller", "Kamehameha spettacolari che sembrano uscite direttamente dalle tavole animate di Toriyama.", "PEGI 12", "Dragon Ball", "#e65100", "#ffeb3b", "🐉"],
  ["Kingdom Hearts III (Xbox One)", "Square Enix", 2019, ["Action RPG"], ["Sora Donald Goofy", "Mondi Pixar", "Keyblade Mutaforma"], "3a Persona", "Sora brandisce il Keyblade insieme a Woody, Buzz, Elsa ed Ercole per la battaglia della luce.", "PEGI 12", "Kingdom Hearts", "#00204a", "#ffd700", "🗝️"],
  ["Yakuza 0 (Xbox One)", "Ryu Ga Gotoku Studio", 2020, ["Action Adventure", "Picchiaduro"], ["Kamurocho Anni 80", "Kazuma Kiryu e Goro Majima"], "3a Persona", "I ruggenti anni Ottanta di Kamurocho: canta al karaoke, gestisci locali e spacca biciclette sui teppisti.", "PEGI 18", "Yakuza", "#3e0000", "#ffb300", "🐉"],
  ["Yakuza: Like a Dragon", "Ryu Ga Gotoku Studio", 2020, ["GDR a Turni"], ["Ichiban Kasuga", "Yokohama", "Evocazioni Bizzarre"], "3a Persona", "Ichiban vede la vita come un gioco di ruolo tra mazzette di denaro e piccioni evocati in battaglia.", "PEGI 18", "Yakuza", "#800020", "#ffca28", "🥊"],
  ["Control", "Remedy Entertainment", 2019, ["Action Adventure"], ["Jesse Faden", "Oldest House", "Telecinesi Spettacolare"], "3a Persona", "Afferra scrivanie e blocchi di cemento con la mente per sconfiggere il misterioso Hiss.", "PEGI 16", "Remedy", "#311b92", "#ff1744", "🏢"],
  ["Alan Wake Remastered (Xbox One)", "Remedy Entertainment", 2021, ["Thriller Psicologico"], ["Bright Falls", "La Torcia Salva-Vita", "Ombre"], "3a Persona", "Usa la luce della torcia per indebolire le ombre oscure prima di sparare nella nebbia.", "PEGI 16", "Alan Wake", "#0a192f", "#00e5ff", "🔦"],
  ["Doom (2016)", "id Software", 2016, ["First-Person Shooter"], ["Doom Slayer", "BFG 9000", "Rip and Tear"], "1a Persona", "Rip and tear, until it is done. Velocità forsennata e gloria brutale al ritmo di Mick Gordon.", "PEGI 18", "Doom", "#1a0000", "#ff1744", "🔥"],
  ["Doom Eternal", "id Software", 2020, ["First-Person Shooter"], ["Meathook", "Lama da Braccio", "Danza della Morte"], "1a Persona", "Il loop di sparo, motosega e lanciafiamme più perfetto e tecnico mai creato per un FPS.", "PEGI 18", "Doom", "#2b0000", "#ff5722", "⚡"],
  ["Wolfenstein: The New Order", "MachineGames", 2014, ["First-Person Shooter"], ["B.J. Blazkowicz", "Resistenza", "Doppio Fucile Pesante"], "1a Persona", "Blazkowicz si risveglia in un 1960 alternativo per guidare la riscossa contro l'oppressione.", "PEGI 18", "Wolfenstein", "#1b1b1b", "#d50000", "🪓"],
  ["Wolfenstein II: The New Colossus", "MachineGames", 2017, ["First-Person Shooter"], ["Terror-Billy", "America Occupata", "Tuta Daat Yichud"], "1a Persona", "Terror-Billy scatena il caos con armature corazzate e fucili pesanti per liberare gli Stati Uniti.", "PEGI 18", "Wolfenstein", "#212121", "#e53935", "🗽"],
  ["Dishonored 2", "Arkane Studios", 2016, ["Immersive Sim", "Stealth"], ["Karnaca", "Corvo ed Emily", "Mansion Meccanica"], "1a Persona", "Infiltrati nella splendida Karnaca scivolando tra i tetti o aprendoti la strada a colpi di spada.", "PEGI 18", "Dishonored", "#002626", "#ffd700", "🐀"],
  ["Prey (2017)", "Arkane Studios", 2017, ["Immersive Sim", "Sci-Fi"], ["Stazione Talos I", "Typhon Mimic", "GLOO Cannon"], "1a Persona", "Qualsiasi tazza di caffè o sedia sulla stazione spaziale Talos I potrebbe essere un mostro mimetico.", "PEGI 18", "Prey", "#0d1b2a", "#ff9800", "☕"],
  ["Fallout 4", "Bethesda Game Studios", 2015, ["Action RPG"], ["Commonwealth di Boston", "Dogmeat", "Costruzione Insediamenti"], "1a Persona", "Costruisci rifugi e armature atomiche esplorando le rovine radioattive del Commonwealth.", "PEGI 18", "Fallout", "#1b263b", "#ffd600", "☢️"],
  ["The Elder Scrolls V: Skyrim - Special Edition", "Bethesda Game Studios", 2016, ["Action RPG"], ["Dovahkiin", "Fus Ro Dah", "Supporto Mod su Console"], "1a Persona", "Fus Ro Dah! La leggenda del Sangue di Drago con pieno supporto alle mod della community.", "PEGI 18", "The Elder Scrolls", "#1c2833", "#00bcd4", "🐲"],
  ["Destiny (Xbox One)", "Bungie", 2014, ["MMO First-Person Shooter"], ["Guardiani", "Volta di Vetro", "Spettro"], "1a Persona", "Diventa leggenda: impugna il Gjallarhorn e difendi l'ultima città della Terra sotto il Viaggiatore.", "PEGI 16", "Destiny", "#0d1b2a", "#ff9100", "🌌"],
  ["Destiny 2", "Bungie", 2017, ["MMO First-Person Shooter"], ["Dominus Ghaul", "Luce Perduta", "Raid Leviatano"], "1a Persona", "I Guardiani riconquistano la Luce sfidando nemici cosmici nei raid più complessi del gaming.", "PEGI 16", "Destiny", "#102027", "#80d8ff", "✨"],
  ["Overwatch", "Blizzard Entertainment", 2016, ["Hero Shooter"], ["Tracer e Genji", "Il Mondo Ha Bisogno di Eroi"], "1a Persona", "Cheers, love! The cavalry's here! Il fenomeno multiplayer che ha unito milioni di giocatori.", "PEGI 12", "Overwatch", "#e65100", "#ffca28", "⏱️"],
  ["Diablo III: Reaper of Souls - Ultimate Evil Edition", "Blizzard Entertainment", 2014, ["Action RPG", "Hack and Slash"], ["Malthael", "Crociato", "Comandi Console Perfetti"], "Isometrica", "La caccia a Malthael giocata a 4 sul divano col controller è un'esperienza imbattibile.", "PEGI 16", "Diablo", "#1a0005", "#ff1744", "💀"],
  ["Apex Legends", "Respawn Entertainment", 2019, ["Battle Royale"], ["King's Canyon", "Sistema di Ping Rivoluzionario"], "1a Persona", "Il sistema di segnalazione a ping che ha cambiato per sempre la comunicazione nei giochi online.", "PEGI 16", "Apex Legends", "#212121", "#ff3d00", "🎯"],
  ["Rainbow Six Siege", "Ubisoft Montreal", 2015, ["Tactical Shooter"], ["Operatori", "Muri Distruttibili", "Tensione Massima"], "1a Persona", "Piazza cariche da irruzione, rinforza le pareti e gioca sulla millimetrica linea di tiro.", "PEGI 18", "Rainbow Six", "#121212", "#29b6f6", "💣"],
  ["Assassin's Creed Origins", "Ubisoft Montreal", 2017, ["Action RPG Open World"], ["Bayek di Siwa", "Antico Egitto", "Nascita degli Occulti"], "3a Persona", "Scala le grandi piramidi di Giza e cavalca attraverso tempeste di sabbia nell'Antico Egitto.", "PEGI 18", "Assassin's Creed", "#3e2723", "#ffc107", "🦅"],
  ["Assassin's Creed Odyssey", "Ubisoft Quebec", 2018, ["Action RPG Open World"], ["Kassandra e Alexios", "Antica Grecia", "Lancia di Leonida"], "3a Persona", "Naviga l'Egeo tra le isole greche e calcia nemici dalle scogliere con lo Spartan Kick.", "PEGI 18", "Assassin's Creed", "#003366", "#ffd700", "🏛️"],
  ["Far Cry 4", "Ubisoft Montreal", 2014, ["First-Person Shooter Open World"], ["Pagan Min", "Kyrat sulle Vette Himalayane", "Cavalcare Elefanti"], "1a Persona", "Pagan Min ti attende nel Kyrat tra sparatorie a dorso d'elefante e lanci con la tuta alare.", "PEGI 18", "Far Cry", "#311b92", "#ff007f", "🏔️"],
  ["Far Cry 5", "Ubisoft Montreal", 2018, ["First-Person Shooter Open World"], ["Joseph Seed", "Hope County Montana", "Co-op Completa"], "1a Persona", "Affronta il culto dell'Eden's Gate tra i fiumi e le foreste mozzafiato del Montana.", "PEGI 18", "Far Cry", "#1b3a1b", "#ff9800", "⛪"],
  ["The Division", "Massive Entertainment", 2016, ["Looter Shooter"], ["New York Innevata", "Virus Black Friday", "Dark Zone"], "3a Persona", "New York sotto la bufera di neve e la tensione palpabile delle estrazioni nella Zona Nera.", "PEGI 18", "The Division", "#1c2833", "#ff6d00", "❄️"],
  ["The Division 2", "Massive Entertainment", 2019, ["Looter Shooter"], ["Washington D.C. Estiva", "Casa Bianca", "Endgame Solido"], "3a Persona", "Riconquista la capitale degli Stati Uniti liberando i quartieri con armi e droni tattici.", "PEGI 18", "The Division", "#263238", "#ff9100", "🏛️"],
  ["Watch Dogs 2", "Ubisoft Montreal", 2016, ["Open World", "Hacking"], ["Marcus Holloway", "DedSec San Francisco", "Droni e Hackerate"], "3a Persona", "Hckera semafori, telecamere e gru a San Francisco guidando i ribelli di DedSec.", "PEGI 18", "Watch Dogs", "#004d40", "#00e5ff", "💻"],
  ["Batman: Arkham Knight", "Rocksteady Studios", 2015, ["Action Adventure"], ["Batmobile Trasformabile", "Cavaliere di Arkham", "Spaventapasseri"], "3a Persona", "Sfreccia tra le strade piovose di Gotham City al volante della Batmobile corazzata.", "PEGI 18", "Batman", "#0d1b2a", "#00bcd4", "🦇"],
  ["Middle-earth: Shadow of Mordor", "Monolith Productions", 2014, ["Action Adventure"], ["Talion e Celebrimbor", "Nemesis System Rivoluzionario"], "3a Persona", "Il Nemesis System crea rivali orchi unici che ricordano ogni cicatrice e sconfitta inflitta.", "PEGI 18", "Middle-earth", "#1a0005", "#ff5722", "💍"],
  ["Middle-earth: Shadow of War", "Monolith Productions", 2017, ["Action Adventure"], ["Assedio alle Fortezze", "Dominio Orchi", "Nuovo Anello"], "3a Persona", "Costruisci il tuo esercito di orchi e guida titanici assedi alle fortezze di Mordor.", "PEGI 18", "Middle-earth", "#21102b", "#ff9800", "🏰"],
  ["Mad Max", "Avalanche Studios", 2015, ["Action Open World", "Combattimento Veicoli"], ["Magnum Opus", "Wasteland", "Harpoon e V8"], "3a Persona", "Personalizza il tuo bolide Magnum Opus e sperona convogli bellici tra le tempeste di sabbia.", "PEGI 18", "Mad Max", "#3e2723", "#ff6f00", "🚗"],
  ["Alien: Isolation", "Creative Assembly", 2014, ["Survival Horror"], ["Amanda Ripley", "Xenomorfo Imprevedibile", "Radar Suoni"], "1a Persona", "Il bip cadenzato del sensore di movimento mentre lo Xenomorfo striscia nei condotti sopra di te.", "PEGI 18", "Alien", "#001a09", "#00ff66", "👽"],
  ["Mortal Kombat 11", "NetherRealm Studios", 2019, ["Picchiaduro"], ["Scorpion e Sub-Zero", "Fatal Blow", "Kronika"], "2D Side-Scroller", "Fatalities iper-dettagliate e una modalità storia cinematografica di prim'ordine.", "PEGI 18", "Mortal Kombat", "#2b0000", "#ffd600", "🩸"],
  ["Tekken 7", "Bandai Namco", 2017, ["Picchiaduro 3D"], ["Scontro Heihachi e Kazuya", "Rage Art", "Akuma Ospite"], "3a Persona", "La resa dei conti finale della faida familiare Mishima sul cratere di un vulcano in fiamme.", "PEGI 16", "Tekken", "#1a0000", "#ff1744", "👊"],
  ["Soulcalibur VI", "Bandai Namco", 2018, ["Picchiaduro con Armi"], ["Soul Edge e Soul Calibur", "Geralt di Rivia", "Reversal Edge"], "3a Persona", "La leggenda delle spade dell'anima rivive con scontri all'ultimo fendente e Geralt di Rivia ospite.", "PEGI 16", "Soulcalibur", "#0d1b2a", "#00e5ff", "⚔️"],
  ["Crash Bandicoot N. Sane Trilogy (Xbox One)", "Vicarious Visions", 2018, ["Platform 3D"], ["Trilogia Rimasterizzata", "Wumpa Fruit", "Aku Aku"], "3a Persona", "La storica trilogia di Crash tirata a lucido con pelliccia dettagliata e controlli moderni.", "PEGI 7", "Crash Bandicoot", "#bf360c", "#ffca28", "🦊"],
  ["Spyro Reignited Trilogy", "Toys for Bob", 2018, ["Platform 3D"], ["Draghetto Viola", "Sparafiamme", "Mondi da Sogno"], "3a Persona", "Spyro vola e plana tra cieli pastello e draghi anziani ricreati con amore infinito.", "PEGI 7", "Spyro", "#311b92", "#ffeb3b", "🐲"],
  ["Sekiro: Shadows Die Twice (GOTY)", "FromSoftware", 2019, ["Action"], ["Spada Kusabimaru", "Braccio Protesico", "Isshin il Santo della Spada"], "3a Persona", "Solo la concentrazione assoluta può portarti alla vittoria nel capolavoro FromSoftware.", "PEGI 18", "Sekiro", "#1b1b1b", "#ff3d00", "🥷"],
  ["Borderlands 3", "Gearbox Software", 2019, ["Looter Shooter"], ["Miliardi di Armi", "Santuario III", "Gemelli Calypso"], "1a Persona", "Miliardi di armi assurde che sparano hamburger, proiettili a tracciamento e camminano su gambe!", "PEGI 18", "Borderlands", "#ff6f00", "#ffd54f", "🔫"],
  ["Life is Strange", "DONTNOD Entertainment", 2015, ["Avventura Narrativa"], ["Max Caulfield", "Chloe Price", "Riavvolgere il Tempo"], "3a Persona", "Riavvolgi il tempo per cambiare le scelte nel racconto di passaggio all'età adulta ad Arcadia Bay.", "PEGI 16", "Life is Strange", "#004d40", "#ff80ab", "🦋"],
  ["Hellblade: Senua's Sacrifice", "Ninja Theory", 2017, ["Action Adventure", "Audio Binaurale"], ["Senua", "Helheim", "Voci nella Mente"], "3a Persona", "Indossa le cuffie per ascoltare le voci bisbigliate nella mente tormentata della guerriera celtica Senua.", "PEGI 18", "Hellblade", "#1a1a1a", "#00e5ff", "🗡️"],
  ["A Plague Tale: Innocence", "Asobo Studio", 2019, ["Action Stealth"], ["Amicia e Hugo", "Marea di Topi Neri", "Fionda e Fuoco"], "3a Persona", "Fuggi dall'Inquisizione nella Francia medievale mentre migliaia di ratti famelici fuggono dalla luce.", "PEGI 18", "A Plague Tale", "#261c14", "#ff9800", "🐀"],
  ["Subnautica", "Unknown Worlds", 2018, ["Sopravvivenza Sottomarina"], ["Pianeta 4546B", "Leviathan", "Base Sottomarina Cyclops"], "1a Persona", "Immergiti nelle acque aliene mozzafiato e terrorizzanti del pianeta oceanico.", "PEGI 7", "Subnautica", "#006064", "#00e5ff", "🌊"],
  ["Outer Wilds", "Mobius Digital", 2019, ["Avventura Esplorativa", "Sci-Fi"], ["Loop di 22 Minuti", "Supernova", "Archeologia Spaziale"], "1a Persona", "Un mistero stellare poetico racchiuso in un loop temporale che esplode ogni 22 minuti.", "PEGI 7", "Outer Wilds", "#1b263b", "#ff9800", "🚀"],
  ["Hollow Knight", "Team Cherry", 2018, ["Metroidvania"], ["Hallownest", "Cavaliere Silenzioso", "Ago e Canto"], "2D Side-Scroller", "Scendi nelle profondità decadenti e malinconiche dell'antico regno degli insetti.", "PEGI 7", "Hollow Knight", "#0d1b2a", "#80d8ff", "🪲"],
  ["Dead Cells", "Motion Twin", 2018, ["Roguevania"], ["Rotolo di Schivata", "Armi Brutali", "Prigioniero Senza Testa"], "2D Side-Scroller", "Azione fulminea, rotolate e fendenti precisi in una prigione in continuo mutamento.", "PEGI 16", "Dead Cells", "#311b92", "#ff1744", "⚔️"],
  ["Celeste", "Maddy Makes Games", 2018, ["Platform di Precisione"], ["Madeline", "Monte Celeste", "Scatto nell'Aria"], "2D Side-Scroller", "Scala il Monte Celeste superando ostacoli millimetrici e imparando ad accettare te stesso.", "PEGI 7", "Celeste", "#004d40", "#ff4081", "🍓"],
  ["Stardew Valley", "ConcernedApe", 2016, ["Simulazione di Fattoria"], ["Pelican Town", "Coltivazioni e Pesca", "Miniere"], "Isometrica", "Ripristina la vecchia fattoria del nonno, stringi amicizie e ritrova la serenità rurale.", "PEGI 7", "Stardew Valley", "#1b5e20", "#ffca28", "🌾"],
  ["Terraria", "Re-Logic", 2014, ["Sandbox Avventura"], ["Scava Combatti Costruisci", "Boss Giganteschi"], "2D Side-Scroller", "Scava nelle viscere della terra per forgiare armi leggendarie e abbattere orrori cosmici.", "PEGI 12", "Terraria", "#0d2b14", "#76ff03", "⛏️"],
  ["Minecraft: Xbox One Edition", "Mojang", 2014, ["Sandbox Sopravvivenza"], ["Mondi Infiniti", "Blocchi e Fantasia", "Drago dell'End"], "1a Persona", "La tela infinita su cui dare forma a qualsiasi creazione della tua immaginazione.", "PEGI 7", "Minecraft", "#1b3a1b", "#8bc34a", "🧱"],
  ["Roblox (Xbox One)", "Roblox Corporation", 2015, ["Sandbox Multigiocatore"], ["Mondi Creati dagli Utenti", "Minigiochi Infiniti"], "3a Persona", "Milioni di esperienze sociali e minigiochi creati quotidianamente da giocatori di tutto il globo.", "PEGI 7", "Roblox", "#b71c1c", "#ffeb3b", "🎲"],
  ["Warframe (Xbox One)", "Digital Extremes", 2014, ["Action Looter Shooter"], ["Ninja Spaziali", "Armature Warframe", "Movimento Fluido"], "3a Persona", "Ninja spaziali acrobatici che sfrecciano a velocità supersonica falciando orde aliene.", "PEGI 18", "Warframe", "#00204a", "#00e5ff", "🥷"],
  ["World of Tanks: Mercenaries", "Wargaming", 2014, ["Combattimento Mezzi"], ["Carri Armati Storici", "Tattica 15v15"], "3a Persona", "Scontri corazzati a 30 giocatori tra veicoli della Seconda Guerra Mondiale riprodotti minuziosamente.", "PEGI 7", "World of Tanks", "#263238", "#ff9800", "🛡️"],
  ["Payday 2: Crimewave Edition", "Overkill Software", 2015, ["Sparatutto Rapine"], ["Maschere da Pagliaccio", "Trapano Termico", "Banche"], "1a Persona", "Pianifica la rapina perfetta in cooperativa a quattro prima che arrivino le teste di cuoio.", "PEGI 18", "Payday", "#1a1a1a", "#29b6f6", "🎭"],
  ["Sniper Elite 4", "Rebellion Developments", 2017, ["Stealth Tattico"], ["Karl Fairburne", "Italia 1943", "Killcam ai Raggi X"], "3a Persona", "La celebre visuale a raggi X rallenta il tempo seguendo i colpi da cecchino nell'Italia del 1943.", "PEGI 18", "Sniper Elite", "#1c2518", "#ff5722", "🎯"],
  ["Hitman (2016)", "IO Interactive", 2016, ["Stealth Immersive Sim"], ["Agente 47", "Parigi Sapienza Marrakesh", "Mille Travestimenti"], "3a Persona", "L'Agente 47 colpisce nell'ombra a Sapienza e Parigi con infinita creatività negli omicidi.", "PEGI 18", "Hitman", "#1a1a1a", "#ff1744", "🍸"]
];

// Additional 50 Xbox Original Games to reach 100 total
const rawXboxOrigExtra = [
  ["Buffy the Vampire Slayer", "The Collective", 2002, ["Action Adventure"], ["Sunnydale", "Paletti di Frassino", "Vampiri"], "3a Persona", "Buffy combatte a calci, pugni e paletti di frassino nel miglior adattamento della serie TV.", "PEGI 16", "Buffy", "#21102b", "#e91e63", "🧛"],
  ["Stubbs the Zombie in Rebel Without a Pulse", "Wideload Games", 2005, ["Action Commedia"], ["Cervelli Freschi", "Punchbowl Città del Futuro"], "3a Persona", "Mangia i cervelli degli umani e guidali in una marcia non-morta contro i poliziotti negli anni 50.", "PEGI 18", "Stubbs", "#1c2833", "#76ff03", "🧠"],
  ["Kingdom Under Fire: The Crusaders", "Phantagram", 2004, ["Strategia e Azione"], ["Guerra Fantasy", "Migliaia di Soldati", "Comando Tattico"], "3a Persona", "Guida centinaia di fanti sul campo tattico prima di scendere nella mischia a colpi di spadone.", "PEGI 16", "Kingdom Under Fire", "#1a0005", "#ff5722", "⚔️"],
  ["Kingdom Under Fire: Heroes", "Phantagram", 2005, ["Strategia e Azione"], ["Sette Nuovi Eroi", "Miglior Bilanciamento"], "3a Persona", "Battaglie campali ancora più colossali con nuove fazioni ed eroi giocabili.", "PEGI 16", "Kingdom Under Fire", "#261c14", "#ffa000", "🛡️"],
  ["Phantom Dust", "Majesco / Microsoft", 2004, ["Azione Carte Tattiche"], ["Mondo Post-Apocalittico", "Oltre 300 Abilità"], "3a Persona", "Un geniale ibrido tra picchiaduro 3D e gioco di carte collezionabili in arene distruttibili.", "PEGI 12", "Phantom Dust", "#0d1b2a", "#00e5ff", "🌪️"],
  ["Gunvalkyrie", "Smilebit", 2002, ["Third-Person Shooter"], ["Tuta a Propulsione", "Comandi Iper-Tecnici"], "3a Persona", "Scatti aerei supersonici e precisione millimetrica contro sciami insettoidi alieni.", "PEGI 12", "Gunvalkyrie", "#00204a", "#ffca28", "🚀"],
  ["Breakdown", "Namco", 2004, ["First-Person Action"], ["Derrick Cole", "T-Hero", "Cazzotti in Prima Persona"], "1a Persona", "L'esperienza in prima persona più fisica e immersiva mai tentata sull'Xbox classica.", "PEGI 16", "Breakdown", "#1b1b1b", "#00e676", "👊"],
  ["Enclave", "Starbreeze Studios", 2002, ["Action Adventure Fantasy"], ["Luce e Oscurità", "Cavalieri e Maghi"], "3a Persona", "Due campagne opposte tra eroi della luce e guerrieri delle tenebre con grafica d'impatto.", "PEGI 16", "Enclave", "#21102b", "#ffd700", "🏰"],
  ["Fatal Frame II: Crimson Butterfly (Director's Cut)", "Tecmo", 2004, ["Survival Horror"], ["Mio e Mayu", "Fotocamera Oscura", "Visuale Prima Persona Esclusiva"], "1a Persona", "La versione definitiva del capolavoro horror giapponese con esclusiva visuale in prima persona.", "PEGI 18", "Fatal Frame", "#1a0000", "#d50000", "📷"],
  ["Silent Hill 2: Restless Dreams (Xbox)", "Konami", 2001, ["Survival Horror"], ["James Sunderland", "Pyramid Head", "Scenario Maria"], "3a Persona", "L'edizione speciale del celebre capolavoro horror che ha introdotto per prima lo scenario Born from a Wish.", "PEGI 18", "Silent Hill", "#1c2518", "#ff9800", "🌫️"],
  ["Silent Hill 4: The Room (Xbox)", "Konami", 2004, ["Survival Horror"], ["Henry Townshend", "Appartamento 302", "Walter Sullivan"], "1a Persona", "Il buco nel bagno dell'appartamento 302 conduce negli incubi più disturbanti di Konami.", "PEGI 18", "Silent Hill", "#261c14", "#c62828", "🚪"],
  ["TimeSplitters 2 (Xbox)", "Free Radical Design", 2002, ["First-Person Shooter"], ["Viaggi Temporali", "Multiplayer a 4 Schermi"], "1a Persona", "Il miglior shooter arcade cooperativo per 4 giocatori da divano sul disco fisso di Xbox.", "PEGI 16", "TimeSplitters", "#003366", "#ffd54f", "🐒"],
  ["TimeSplitters: Future Perfect", "Free Radical Design", 2005, ["First-Person Shooter"], ["Cortez", "Time to split!", "Fucile Gravitazionale"], "1a Persona", "It's time to split! Cortez incontra i suoi alter ego del futuro in sparatorie esilaranti.", "PEGI 16", "TimeSplitters", "#1a237e", "#ff3d00", "⏳"],
  ["Burnout 2: Point of Impact", "Criterion Games", 2003, ["Corse Arcade"], ["Crash Mode Debutto", "Incidenti a Catena"], "3a Persona", "Il debutto dell'amatissima modalità Crash in cui massimizzare i danni negli incroci.", "PEGI 3", "Burnout", "#800000", "#ffca28", "💥"],
  ["Midtown Madness 3", "DICE", 2003, ["Guida Arcade Open World"], ["Parigi e Washington D.C.", "Xbox Live Online"], "3a Persona", "Guida furgoni per le consegne e taxi tra gli Champs-Élysées e il Campidoglio americano.", "PEGI 3", "Midtown Madness", "#0d47a1", "#ffd600", "🚕"],
  ["Brothers in Arms: Road to Hill 30", "Gearbox Software", 2005, ["Tactical Shooter WWII"], ["101a Aviotrasportata", "Tattica dei 4 F", "Matt Baker"], "1a Persona", "Fissa il nemico sul posto con la squadra di fuoco e aggiralo con la squadra d'assalto.", "PEGI 16", "Brothers in Arms", "#1c2518", "#8bc34a", "🪖"],
  ["Brothers in Arms: Earned in Blood", "Gearbox Software", 2005, ["Tactical Shooter WWII"], ["Joe Hartsock", "Battaglie Urbane in Normandia"], "1a Persona", "L'IA tedesca più aggressiva e reattiva mette alla prova ogni singola decisione tattica.", "PEGI 16", "Brothers in Arms", "#263238", "#ff9800", "🎖️"],
  ["Call of Duty 2: Big Red One", "Treyarch", 2005, ["First-Person Shooter"], ["Prima Divisione Fanteria", "Campagna d'Italia"], "1a Persona", "Vivi i legami fraterni dei soldati americani tra il Nord Africa, la Sicilia e la Germania.", "PEGI 16", "Call of Duty", "#1b263b", "#ffc107", "⭐"],
  ["Medal of Honor: Frontline (Xbox)", "EA Los Angeles", 2002, ["First-Person Shooter"], ["Sbarco in Normandia", "Jimmy Patterson"], "1a Persona", "Lo sbarco a Omaha Beach con audio surround e colonna sonora orchestrale indimenticabile.", "PEGI 12", "Medal of Honor", "#1c2833", "#78909c", "🏖️"],
  ["Medal of Honor: European Assault", "EA Los Angeles", 2005, ["First-Person Shooter"], ["William Holt", "Adrenalina", "Operazioni OSS"], "1a Persona", "Obiettivi aperti e la barra dell'Adrenalina per colpi letali dietro le linee nemiche.", "PEGI 16", "Medal of Honor", "#212121", "#e53935", "🎯"],
  ["Full Spectrum Warrior", "Pandemic Studios", 2004, ["Strategia Tattica Militare"], ["Dottrina US Army", "Zero Sparo Diretto", "Coperture"], "3a Persona", "Sviluppato originariamente come simulatore d'addestramento tattico per l'esercito americano.", "PEGI 16", "Full Spectrum", "#3e2723", "#ffb300", "🛡️"],
  ["Ghost Recon (Xbox)", "Red Storm Entertainment", 2002, ["Tactical Shooter"], ["Berretti Verdi", "Xbox Live Pioniere", "Morte in un Colpo"], "1a Persona", "Il primo grande fenomeno competitivo tattico su Xbox Live: un solo proiettile ed è finita.", "PEGI 16", "Ghost Recon", "#0d1b2a", "#00e676", "🌿"],
  ["Ghost Recon 2", "Red Storm Entertainment", 2004, ["Tactical Shooter"], ["Scott Mitchell", "Nuova Grafica e Over-the-shoulder"], "3a Persona", "Scott Mitchell debutta alla guida dei Ghost con visuale da dietro le spalle innovativa.", "PEGI 16", "Ghost Recon", "#102027", "#29b6f6", "🎯"],
  ["Rainbow Six 3 (Xbox)", "Ubisoft Montreal", 2003, ["Tactical Shooter"], ["Ding Chavez", "Ordini Vocali con Headset", "Pianificazione"], "1a Persona", "Dai comandi vocali alla tua squadra d'assalto parlando direttamente nel microfono dell'headset!", "PEGI 16", "Rainbow Six", "#1a1a1a", "#e53935", "🎙️"],
  ["Rainbow Six 3: Black Arrow", "Ubisoft Montreal", 2004, ["Tactical Shooter"], ["Reattore Nucleare", "Multiplayer Competitivo"], "1a Persona", "Uno dei giochi più giocati in assoluto sui server Xbox Live nei primi anni 2000.", "PEGI 16", "Rainbow Six", "#0a190f", "#00e5ff", "⚡"],
  ["Colin McRae Rally 04", "Codemasters", 2004, ["Rally Simulazione"], ["Fisica delle Sospensioni", "Ford Focus WRC"], "3a Persona", "Il feeling di guida su sterrato più realistico e apprezzato dagli appassionati dell'epoca.", "PEGI 3", "Colin McRae", "#003366", "#ff3d00", "🚗"],
  ["Colin McRae Rally 2005", "Codemasters", 2004, ["Rally"], ["Multiplayer Online", "Oltre 30 Auto da Corsa"], "3a Persona", "Sfide di traverso e derapata contro altri piloti sui server di gioco Xbox Live.", "PEGI 3", "Colin McRae", "#00204a", "#ffca28", "🏁"],
  ["TOCA Race Driver 2", "Codemasters", 2004, ["Corse Multidisciplinari"], ["DTM V8 Supercars Camion", "Fisica Danni Reale"], "1a Persona", "Oltre quindici discipline automobilistiche diverse tra monoposto, camion e supercar.", "PEGI 3", "TOCA", "#1a0000", "#ff1744", "🏎️"],
  ["Sega GT 2002", "Smilebit / Wow Entertainment", 2002, ["Simulazione di Guida"], ["Carriera Ufficiale", "Sega Drag Strip"], "1a Persona", "La risposta di SEGA a Gran Turismo con restauro di auto d'epoca e gare cronometrate.", "PEGI 3", "Sega GT", "#0d47a1", "#00e5ff", "🚗"],
  ["Spikeout: Battle Street", "Dimps / SEGA", 2005, ["Picchiaduro a Scorrimento"], ["Azione Arcade Sega", "Co-op Online a 4"], "3a Persona", "La leggendaria rissa da sala giochi SEGA approda a casa con co-op a 4 giocatori online.", "PEGI 16", "Spikeout", "#b71c1c", "#ffd700", "👊"],
  ["Blood Wake", "Stormfront Studios", 2001, ["Combattimento Navale Arcade"], ["Motoscafi Armati di Mitragliatrici", "Fisica delle Onde"], "3a Persona", "Salto sulle onde e siluri contro motoscafi nemici nel colorato titolo di lancio Xbox.", "PEGI 12", "Blood Wake", "#00363a", "#00e5ff", "🚤"],
  ["Deathrow", "SouthEnd Interactive", 2002, ["Sport Futuristico Violento"], ["Blitz Disc", "Rissa Senza Regole"], "3a Persona", "Un brutale sport del futuro dove puoi vincere segnando mete o mandando tutti i rivali all'ospedale.", "PEGI 16", "Deathrow", "#311b92", "#76ff03", "🥏"],
  ["Quantum Redshift", "Curly Monsters", 2002, ["Corse Futuristiche Anti-Gravità"], ["Effetti Acqua sul Parabrezza", "Velocità Folle"], "1a Persona", "Wipeout incontra la potenza di Xbox: gocce di pioggia spettacolari e velocità supersoniche.", "PEGI 3", "Quantum Redshift", "#001064", "#00e5ff", "🚀"],
  ["Whacked!", "Presto Studios", 2002, ["Party Game Folle"], ["Show Televisivo per la Salvezza", "Pupazzi Mutanti"], "3a Persona", "Un game show infernale dove personaggi bizzarri si scontrano per conquistare un desiderio.", "PEGI 12", "Whacked", "#e65100", "#ffeb3b", "📺"],
  ["Voodoo Vince", "Beep Industries", 2003, ["Platform 3D"], ["Bambola Voodoo", "New Orleans", "Autolesionismo Magico"], "3a Persona", "Per sconfiggere i nemici devi farti schiacciare, bruciare o affettare: loro sentiranno il tuo dolore!", "PEGI 7", "Voodoo Vince", "#261c14", "#8bc34a", "🪡"],
  ["Blinx: The Time Sweeper", "Artoon", 2002, ["Platform 3D", "Manipolazione Temporale"], ["Gatto con Aspirapolvere", "Play Pause Rewind"], "3a Persona", "Riavvolgi, metti in pausa e registra il tempo sfruttando per primo l'hard disk della console.", "PEGI 3", "Blinx", "#1a237e", "#ffd54f", "🐱"],
  ["Blinx 2: Masters of Time & Space", "Artoon", 2004, ["Platform 3D"], ["Gatti del Tempo e Maiali dello Spazio"], "3a Persona", "Crea la tua squadra personalizzata controllando i varchi dimensionali dello spazio e del tempo.", "PEGI 7", "Blinx", "#0d47a1", "#ff4081", "🐷"],
  ["Kakuto Chojin", "Dream Publishing", 2002, ["Picchiaduro 3D"], ["Illuminazione Poligonale Straordinaria"], "3a Persona", "Il picchiaduro che ha mostrato le meraviglie dell'illuminazione dinamica sui muscoli dei lottatori.", "PEGI 16", "Kakuto Chojin", "#1a0005", "#ff1744", "🥊"],
  ["Tao Feng: Fist of the Lotus", "Studio Gigante", 2003, ["Picchiaduro 3D"], ["John Tobias", "Ossa Rotte e Vestiti Strappati"], "3a Persona", "Il co-creatore di Mortal Kombat introduce danni localizzati ai muscoli e abiti che si lacerano.", "PEGI 18", "Tao Feng", "#3e0000", "#ffca28", "🥋"],
  ["Unreal Championship", "Epic Games / Digital Extremes", 2002, ["Arena First-Person Shooter"], ["Lancio Xbox Live", "Flak Cannon", "Shock Rifle"], "1a Persona", "L'Unreal Tournament dei campioni porta l'adrenalina delle arene competitive su Xbox Live.", "PEGI 16", "Unreal", "#212121", "#ff6d00", "⚡"],
  ["Unreal Championship 2: The Liandri Conflict", "Epic Games", 2005, ["Arena Action Shooter"], ["Visuale Terza Persona", "Spade Riflettenti", "Raiden Giocabile"], "3a Persona", "Capolavoro d'ibridazione tra sparatutto frenetico e combattimenti a fil di spada acrobatici.", "PEGI 16", "Unreal", "#0d1b2a", "#00e5ff", "🗡️"],
  ["Armed and Dangerous", "Planet Moon Studios", 2003, ["Action Shooter Commedia"], ["Arma che Ribalta il Mondo", "Squalo da Terra"], "3a Persona", "Armi comiche geniali come la granata a buco nero e il cannone che lancia squali nel terreno.", "PEGI 12", "Armed and Dangerous", "#261c14", "#ff9800", "🦈"],
  ["Galleon", "Confounding Factor", 2004, ["Action Adventure 3D"], ["Toby Gard Padre di Lara Croft", "Rhama Sabrier"], "3a Persona", "Toby Gard reinventa le acrobazie dei pirati tra arrampicate su velieri e salti nell'abisso.", "PEGI 12", "Galleon", "#002b4d", "#ffd700", "🏴‍☠️"],
  ["Scrapland (Xbox)", "MercurySteam", 2005, ["Action Adventure Sci-Fi"], ["D-Tritus", "American McGee", "Trasformarsi in 15 Robot"], "3a Persona", "D-Tritus si trasforma in quindici automi diversi per svelare l'omicidio dell'arcivescovo.", "PEGI 12", "Scrapland", "#102027", "#00e676", "🤖"],
  ["Advent Rising", "GlyphX Games", 2005, ["Action Shooter Sci-Fi"], ["Gideon Wyeth", "Orson Scott Card", "Poteri Psichici"], "3a Persona", "La colossale space opera scritta dal celebre romanziere Orson Scott Card.", "PEGI 12", "Advent Rising", "#0a192f", "#29b6f6", "🌌"],
  ["Hunter: The Reckoning (Xbox)", "High Voltage Software", 2002, ["Action Hack and Slash Co-op"], ["Mondo di Tenebra", "4 Cacciatori Insieme"], "Isometrica", "Quattro cacciatori liberano la prigione di Ashdown infestata da vampiri e licantropi.", "PEGI 18", "Hunter", "#1a0000", "#ff1744", "🧛"],
  ["Buffy the Vampire Slayer: Chaos Bleeds", "Eurocom", 2003, ["Action Adventure"], ["Buffy Xander Willow Spike", "Kakistos"], "3a Persona", "Controlla tutti i membri della Scooby Gang per sigillare la Bocca dell'Inferno.", "PEGI 16", "Buffy", "#1a0d24", "#e040fb", "🦇"],
  ["Serious Sam (Xbox)", "Croteam", 2002, ["First-Person Shooter"], ["Migliaia di Nemici Urlanti", "Cannone a Palle di Ferro"], "1a Persona", "Orde sterminate di mostri decapitati urlanti spazzate via a colpi di doppietta ed esplosivi.", "PEGI 16", "Serious Sam", "#3e2723", "#ffd600", "💣"],
  ["Dungeons & Dragons: Heroes", "Atari Hunt Valley", 2003, ["Action RPG Hack and Slash"], ["4 Eroi sul Divano", "D&D Terza Edizione"], "Isometrica", "Il miglior dungeon crawler cooperativo da salotto con guerriero, mago, ladro e chierico.", "PEGI 12", "Dungeons & Dragons", "#1a237e", "#ffca28", "🎲"],
  ["Totaled! (Crash)", "Rage Software", 2002, ["Demolition Derby"], ["Distruzione Lamiere", "Arene Spettacolari"], "3a Persona", "Schianti devastanti a piena velocità per ridurre in rottami le carcasse degli avversari.", "PEGI 3", "Totaled", "#800000", "#ff9800", "💥"]
];

// Combine Xbox Original into 100 Games
const rawXboxOrigComplete = [...rawXboxOrig, ...rawXboxOrigExtra];

writeConsoleFile('src/data/consoles/xboxOriginalGames.ts', 'XBOX_ORIGINAL_GAMES', mapGames(rawXboxOrigComplete, 'Xbox'));
writeConsoleFile('src/data/consoles/xboxOneGames.ts', 'XBOX_ONE_GAMES', mapGames(rawXboxOne, 'Xbox One'));

console.log('Xbox Original Complete count:', rawXboxOrigComplete.length);
console.log('Xbox One Complete count:', rawXboxOne.length);
