import fs from 'fs';
import { generateBoxArtSvg } from './generator_helpers.js';

function writeConsoleFile(filename, varName, games) {
  const code = `import { VideoGameItem } from '../../types';

export const ${varName}: VideoGameItem[] = ${JSON.stringify(games, null, 2)};
`;
  fs.writeFileSync(filename, code, 'utf-8');
  console.log(`Wrote ${games.length} games to ${filename}`);
}

function mapGames(rawList, consoleKey, mainPlatform = 'Nintendo') {
  return rawList.map(([title, dev, year, genres, themes, perspective, quote, pegi, franchise, bg, accent, icon]) => ({
    id: `${consoleKey.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}`,
    title,
    developer: dev,
    releaseYear: year,
    genres,
    themes,
    perspective,
    mainPlatform,
    platforms: [consoleKey],
    iconicQuote: quote,
    coverUrl: generateBoxArtSvg({
      title,
      consoleKey,
      developer: dev,
      year,
      genre: genres[0],
      pegi,
      themeBg: bg,
      accentColor: accent,
      iconSymbol: icon
    }),
    pegi,
    gameModes: ['Giocatore singolo'],
    franchise
  }));
}

// GameCube Iconic Games (50 Masterpieces)
const rawGamecube = [
  ["Super Smash Bros. Melee", "HAL Laboratory", 2001, ["Picchiaduro Platform"], ["Fox Falco Marth", "Wavedash", "Competitivo Leggendario"], "2D Side-Scroller", "La velocità e la precisione tecnica che hanno definito la storia dei picchiaduro competitivi.", "PEGI 3", "Super Smash Bros.", "#1a0033", "#ffd700", "🏆"],
  ["The Legend of Zelda: The Wind Waker", "Nintendo EAD", 2002, ["Action Adventure"], ["Grande Mare", "Link Cartone Cel-Shading", "Bacchetta dei Venti"], "3a Persona", "Spiega le vele sul Grande Mare guidando il vento con la leggendaria Bacchetta.", "PEGI 3", "The Legend of Zelda", "#003366", "#00e5ff", "⛵"],
  ["The Legend of Zelda: Twilight Princess (GameCube)", "Nintendo EAD", 2006, ["Action Adventure"], ["Regno del Crepuscolo", "Link Lupo e Midna", "Spada Suprema"], "3a Persona", "L'avventura più cupa ed epica di Link al fianco dell'irriverente Midna nel Crepuscolo.", "PEGI 12", "The Legend of Zelda", "#1c2518", "#ffd54f", "🐺"],
  ["Super Mario Sunshine", "Nintendo EAD", 2002, ["Platform 3D"], ["Isola Delfino", "SPLAC 3000 Idrogetto", "Mario Ombra"], "3a Persona", "Ripulisci le spiagge e i tetti dell'Isola Delfino a colpi di getto d'acqua pressurizzata.", "PEGI 3", "Super Mario", "#01579b", "#ffeb3b", "🏖️"],
  ["Metroid Prime", "Retro Studios", 2002, ["Action Adventure", "Prima Persona"], ["Tallon IV", "Visore Scansione Samus", "Passaggio al 3D Perfetto"], "1a Persona", "La transizione in prima persona più magistrale della storia: isolamento e scansione su Tallon IV.", "PEGI 12", "Metroid", "#002b1f", "#ff9800", "🛸"],
  ["Metroid Prime 2: Echoes", "Retro Studios", 2004, ["Action Adventure"], ["Pianeta Aether", "Mondo Chiaro e Oscuro", "Samus Oscura"], "1a Persona", "Sopravvivi all'atmosfera caustica di Aether Oscuro e affronta la letale Samus Oscura.", "PEGI 12", "Metroid", "#1a0024", "#e040fb", "🌑"],
  ["Luigi's Mansion", "Nintendo EAD", 2001, ["Action Adventure"], ["Palazzo Infestato", "Poltergust 3000", "Re Boo"], "3a Persona", "Luigi trema di paura ma aspira fantasmi col fidato Poltergust per salvare Mario.", "PEGI 3", "Super Mario", "#00241b", "#76ff03", "👻"],
  ["Mario Kart: Double Dash!!", "Nintendo EAD", 2003, ["Corse Kart"], ["Due Piloti per Kart", "Oggetti Speciali Unici", "Scambio Posto"], "3a Persona", "Due piloti sullo stesso kart: uno al volante e l'altro pronto a lanciare gusci giganti e banane!", "PEGI 3", "Mario Kart", "#b71c1c", "#ffeb3b", "🏎️"],
  ["Paper Mario: Il Portale Millenario", "Intelligent Systems", 2004, ["GDR"], ["Fannullopoli", "Teatro di Battaglia", "Mille Forme di Carta"], "2D Side-Scroller", "Il culmine dell'umorismo e del combattimento a teatro di Paper Mario a Fannullopoli.", "PEGI 3", "Paper Mario", "#3e2723", "#ffca28", "📜"],
  ["Pikmin", "Nintendo EAD", 2001, ["Strategia in Tempo Reale"], ["Capitano Olimar", "30 Giorni per Salvarsi", "Cipolle e Pikmin Rossi Blu Gialli"], "Isometrica", "Comanda sciami di adorabili Pikmin per recuperare i pezzi della navicella Dolphin.", "PEGI 3", "Pikmin", "#1b3a1b", "#ff1744", "🌱"],
  ["Pikmin 2", "Nintendo EAD", 2004, ["Strategia"], ["Olimar e Louie", "Pikmin Viola e Bianchi", "Dungeon Sotterranei"], "Isometrica", "Raccogli tesori stravaganti nelle caverne senza il limite dei 30 giorni.", "PEGI 3", "Pikmin", "#0d2b14", "#76ff03", "🌸"],
  ["F-Zero GX", "Amusement Vision / SEGA", 2003, ["Corse Futuristiche"], ["Capitan Falcon", "60 FPS Fulminei", "Difficoltà Leggendaria"], "1a Persona", "La velocità più pura e brutale del gaming a oltre 2000 chilometri orari senza sconti.", "PEGI 3", "F-Zero", "#0d47a1", "#ffd600", "⚡"],
  ["Animal Crossing (GameCube)", "Nintendo EAD", 2001, ["Simulazione di Vita"], ["Orologio in Tempo Reale", "Tom Nook", "K.K. Slider"], "Isometrica", "Il primo villaggio in tempo reale: pesca, scava fossili e ascolta K.K. alla stazione.", "PEGI 3", "Animal Crossing", "#2e7d32", "#fff59d", "🍃"],
  ["Resident Evil 4 (GameCube)", "Capcom", 2005, ["Survival Horror Action"], ["Leon S. Kennedy", "Telecamera Dietro la Spalla", "Las Plagas"], "3a Persona", "La rivoluzione totale degli action in terza persona con Leon tra i Los Illuminados in Spagna.", "PEGI 18", "Resident Evil", "#1a0000", "#ff1744", "⛓️"],
  ["Resident Evil (Remake Rebirth)", "Capcom", 2002, ["Survival Horror"], ["Villa Spencer", "Crimson Head", "Sfondi Pre-renderizzati Fotografici"], "3a Persona", "Il gold standard dei remake videoludici: terrore puro e Crimson Head a Villa Spencer.", "PEGI 18", "Resident Evil", "#1b1b1b", "#c62828", "🧟"],
  ["Resident Evil Zero", "Capcom", 2002, ["Survival Horror"], ["Rebecca Chambers e Billy Coen", "Partner Zapping"], "3a Persona", "Scambia in tempo reale tra Rebecca e Billy a bordo del treno Eclipse Express.", "PEGI 18", "Resident Evil", "#261c14", "#ff5722", "🚂"],
  ["Eternal Darkness: Sanity's Requiem", "Silicon Knights", 2002, ["Horror Psicologico"], ["Effetti di Sanità Mentale", "Mito di Cthulhu", "Quattro Dee Antiche"], "3a Persona", "Il gioco che rompe la quarta parete simulando volumi che si azzerano e cancellazioni di salvataggio!", "PEGI 18", "Eternal Darkness", "#120024", "#00e5ff", "👁️"],
  ["Star Wars Rogue Squadron II: Rogue Leader", "Factor 5", 2001, ["Simulazione Volo Arcade"], ["Attacco alla Morte Nera", "Grafica Fotorealistica"], "3a Persona", "Il miracolo grafico che ha fatto gridare al prodigio al lancio della console.", "PEGI 3", "Star Wars", "#0d1b2a", "#ffd54f", "🚀"],
  ["Star Wars Rogue Squadron III: Rebel Strike", "Factor 5", 2003, ["Azione Spaziale"], ["Battaglia di Hoth", "Co-op Rogue Leader Completa"], "3a Persona", "Rivivi la caduta degli AT-AT a Hoth e gioca l'intera campagna precedente in co-op a due.", "PEGI 12", "Star Wars", "#102027", "#29b6f6", "❄️"],
  ["Metal Gear Solid: The Twin Snakes", "Silicon Knights / Konami", 2004, ["Stealth Action"], ["Shadow Moses", "Regia di Ryuhei Kitamura", "Motore di MGS2"], "3a Persona", "Solid Snake a Shadow Moses con la visuale in prima persona e le cinematiche d'azione esagerate.", "PEGI 16", "Metal Gear", "#1a252f", "#00e676", "🦊"],
  ["Tales of Symphonia", "Namco Tales Studio", 2003, ["Action RPG"], ["Lloyd Irving", "Colette e la Rigenerazione", "Battaglie a Linea Multipla"], "3a Persona", "Lloyd intraprende il viaggio per salvare due mondi gemelli condannati a scambiarsi il mana.", "PEGI 12", "Tales of", "#003366", "#ffd700", "🗡️"],
  ["Baten Kaitos: Eternal Wings and the Lost Ocean", "Monolith Soft", 2003, ["GDR con Carte"], ["Isole Fluttuanti", "Magnus", "Kalas e Xelha"], "Isometrica", "Mondi sospesi tra le nuvole e un sistema di combattimento con carte Magnus profondo e raffinato.", "PEGI 12", "Baten Kaitos", "#21102b", "#00e5ff", "🪽"],
  ["Baten Kaitos Origins", "Monolith Soft", 2006, ["GDR"], ["Sagi Guillo Milly", "Precedente Storico", "Imperium"], "Isometrica", "Il prequel che perfeziona il mazzo unico di carte e svela i segreti dell'antico impero.", "PEGI 12", "Baten Kaitos", "#1a0033", "#ff4081", "✨"],
  ["Fire Emblem: Path of Radiance", "Intelligent Systems", 2005, ["Strategia a Turni"], ["Ike", "Mercenari di Greil", "Laguz e Beorc"], "Isometrica", "Ike debutta guidando i Mercenari di Greil nella guerra tra umani Beorc e mutaforma Laguz.", "PEGI 12", "Fire Emblem", "#002171", "#ffd700", "🛡️"],
  ["Chibi-Robo!", "Skip Ltd.", 2005, ["Platform Adventure"], ["Robottino con Presa Elettrica", "Famiglia Sanderson"], "3a Persona", "Un minuscolo robot alto dieci centimetri che pulisce casa per donare felicità alla famiglia.", "PEGI 3", "Chibi-Robo", "#ff6f00", "#76ff03", "🔌"],
  ["Viewtiful Joe", "Clover Studio / Capcom", 2003, ["Picchiaduro 2D Cel-Shaded"], ["Henshin a-go-go baby!", "VFX Slow Mach Zoom"], "2D Side-Scroller", "Henshin a-go-go, baby! Rallenta e accelera il tempo come un supereroe sul set cinematografico.", "PEGI 12", "Viewtiful Joe", "#b71c1c", "#ffeb3b", "🎬"],
  ["Viewtiful Joe 2", "Clover Studio / Capcom", 2004, ["Picchiaduro 2D"], ["Joe e Silvia", "Nuovi Poteri VFX"], "2D Side-Scroller", "Silvia si unisce alla festa sparando colpi energetici accanto al leggendario Joe.", "PEGI 12", "Viewtiful Joe", "#880e4f", "#00e5ff", "🦸"],
  ["Killer7", "Grasshopper Manufacture / Capcom", 2005, ["Action Noir Rail Shooter"], ["Goichi Suda Suda51", "Harman Smith e le 7 Personalità"], "1a Persona", "Lo stile visionario e spiazzante di Suda51: un anziano in sedia a rotelle e i suoi sette sicari psichici.", "PEGI 18", "Killer7", "#1b1b1b", "#ff1744", "🎯"],
  ["Wario World", "Treasure", 2003, ["Platform Picchiaduro"], ["Wario Ruba-Tesori", "Prese Giganti"], "3a Persona", "La maestria di Treasure infusa in Wario che esegue piledriver e trottole colossali sui mostri.", "PEGI 3", "Wario", "#ffd600", "#7b1fa2", "💰"],
  ["WarioWare, Inc.: Mega Party Games!", "Nintendo R&D1", 2003, ["Party Game"], ["Microgiochi da 5 Secondi", "Follia a 4 Giocatori"], "2D Side-Scroller", "Reazioni fulminee in microgiochi da cinque secondi che mettono a dura prova l'amicizia!", "PEGI 3", "WarioWare", "#ffeb3b", "#e91e63", "👃"],
  ["Super Mario Strikers", "Next Level Games", 2005, ["Calcio Arcade"], ["Pallonate Elettriche", "Super Tiri Inarrestabili"], "Isometrica", "Il calcio più cattivo, violento ed esilarante della storia del Regno dei Funghi.", "PEGI 3", "Super Mario", "#d50000", "#76ff03", "⚽"],
  ["Mario Power Tennis", "Camelot Software Planning", 2004, ["Tennis Arcade"], ["Super Colpi Difensivi e Offensivi", "Campi Bizzarri"], "3a Persona", "Scambi spettacolari all'ultimo rimbalzo con super colpi infuocati ed effetti speciali.", "PEGI 3", "Super Mario", "#00c853", "#ffd600", "🎾"],
  ["Mario Golf: Toadstool Tour", "Camelot Software Planning", 2003, ["Golf"], ["Fisica della Pallina Raffinata", "Campi del Regno dei Funghi"], "3a Persona", "Tiri di precisione millimetrica tra Warp Pipe, piante Piranha e bunker di sabbia.", "PEGI 3", "Super Mario", "#2e7d32", "#ffeb3b", "⛳"],
  ["Mario Superstar Baseball", "Namco / Nintendo", 2005, ["Baseball Arcade"], ["Lanci Curvi Speciali", "Chimica di Squadra"], "3a Persona", "Lancia palle curve infuocate e batti fuoricampo con la mazza chiodata di Bowser.", "PEGI 3", "Super Mario", "#01579b", "#ff3d00", "⚾"],
  ["Mario Party 4", "Hudson Soft", 2002, ["Party Game"], ["Festa di Compleanno", "Minigiochi Classici Hudson"], "Isometrica", "Il primo Mario Party a 128-bit con la purezza dei tabelloni classici di Hudson Soft.", "PEGI 3", "Mario Party", "#1565c0", "#ffeb3b", "🎲"],
  ["Mario Party 5", "Hudson Soft", 2003, ["Party Game"], ["Mondo dei Sogni", "Capsule Oggetto"], "Isometrica", "I sogni prendono vita sul tabellone con capsule trappola da lanciare sugli avversari.", "PEGI 3", "Mario Party", "#2e7d32", "#ff5722", "🎈"],
  ["Mario Party 6", "Hudson Soft", 2004, ["Party Game"], ["Ciclo Giorno e Notte", "Microfono GameCube Incluso"], "Isometrica", "I tabelloni mutano completamente tra il giorno e la notte con minigiochi a comando vocale.", "PEGI 3", "Mario Party", "#00838f", "#ffd54f", "🎙️"],
  ["Donkey Kong Jungle Beat", "Nintendo EAD Tokyo", 2004, ["Platform Musicale"], ["Bonghi DK Bongo", "Acrobazie a Ritmo"], "2D Side-Scroller", "Suona e applaudi sui veri bonghi per far compiere balzi supersonici a Donkey Kong!", "PEGI 3", "Donkey Kong", "#e65100", "#ffd600", "🪘"],
  ["Star Fox Adventures", "Rare", 2002, ["Action Adventure 3D"], ["Pianeta Sauria", "Bastone Magico di Krystal", "Pelliccia da Record"], "3a Persona", "L'ultimo capolavoro visivo di Rare per Nintendo: dinosauri, magia e pellicce mozzafiato.", "PEGI 3", "Star Fox", "#1b5e20", "#00e5ff", "🦊"],
  ["Star Fox: Assault", "Namco", 2005, ["Action Shooter"], ["Battaglie a Terra e in Arwing", "Invasione Aparoidi"], "3a Persona", "Alterna scontri aerei ad alta quota su Arwing e battaglie con lanciamissili a terra.", "PEGI 12", "Star Fox", "#0d47a1", "#00e676", "🚀"],
  ["1080° Avalanche", "Nintendo NST", 2003, ["Snowboard Arcade"], ["Valanghe Improvvise", "Colonna Sonora Punk Rock"], "3a Persona", "Sfreccia a valle mentre una colossale muraglia di neve e ghiaccio si sgretola dietro di te.", "PEGI 3", "1080", "#0277bd", "#e0f7fa", "🏂"],
  ["Wave Race: Blue Storm", "Nintendo NST", 2001, ["Moto d'Acqua Arcade"], ["Fisica delle Onde Tempestose", "Meteo Dinamico"], "3a Persona", "La simulazione fisica della superficie marina più impressionante dell'inizio degli anni 2000.", "PEGI 3", "Wave Race", "#00695c", "#80d8ff", "🌊"],
  ["Custom Robo", "Noise / Nintendo", 2004, ["Action Robot Arena"], ["Robo Personalizzabili", "Ologrammi da Battaglia"], "3a Persona", "Assembla cannoni, propulsori e pod esplosivi sul tuo robottino da combattimento olografico.", "PEGI 7", "Custom Robo", "#37474f", "#ff9100", "🤖"],
  ["Battalion Wars", "Kuju Entertainment", 2005, ["Strategia e Azione"], ["Comando Fanteria e Carri", "Federazione Occidentale"], "3a Persona", "Guida direttamente fanti e blindati sparando in terza persona mentre ordini gli attacchi di squadra.", "PEGI 12", "Wars", "#263238", "#ff3d00", "🪖"],
  ["Geist", "n-Space / Nintendo", 2005, ["Action Adventure", "Prima Persona"], ["Spettro John Raimi", "Possedere Oggetti e Persone"], "1a Persona", "Possiedi cani, piatti doccia, guardie armate ed esplosivi per aprirti la fuga dal laboratorio.", "PEGI 16", "Geist", "#120024", "#00e5ff", "👻"],
  ["Sonic Adventure 2: Battle", "Sonic Team", 2001, ["Platform 3D"], ["Sonic e Shadow", "Chao Garden Definitivo"], "3a Persona", "Hero vs Dark: la rivalità leggendaria tra Sonic e Shadow e le ore spese ad allevare i teneri Chao.", "PEGI 3", "Sonic", "#0d47a1", "#ffd600", "🦔"],
  ["Sonic Heroes (GameCube)", "Sonic Team", 2003, ["Platform 3D"], ["Team Sonic Dark Rose Chaotix", "60 FPS Esclusivi"], "3a Persona", "Velocità, Volo e Potenza: la versione GameCube è l'unica a girare a 60 frame al secondo perfetti.", "PEGI 3", "Sonic", "#002171", "#ff1744", "⚡"],
  ["Super Monkey Ball", "Amusement Vision / SEGA", 2001, ["Puzzle Platform di Precisione"], ["Scimmie nella Sfera", "Inclinare il Pavimento"], "3a Persona", "Inclina il pavimento con precisione chirurgica per guidare la scimmietta al traguardo.", "PEGI 3", "Super Monkey Ball", "#ff6f00", "#ffeb3b", "🍌"],
  ["Super Monkey Ball 2", "Amusement Vision / SEGA", 2002, ["Puzzle Platform"], ["Modalità Storia Folle", "Monkey Target Minigioco"], "3a Persona", "Il minigioco Monkey Target con atterraggio sul bersaglio oceanico ha fatto epoca!", "PEGI 3", "Super Monkey Ball", "#e65100", "#76ff03", "🎯"],
  ["Ikaruga (GameCube)", "Treasure", 2003, ["Shoot 'em Up"], ["Bianco e Nero", "Polarità Energetica", "Capolavoro Assoluto"], "2D Side-Scroller", "Assorbi i proiettili dello stesso colore e scatena il laser sui nemici della polarità opposta.", "PEGI 3", "Ikaruga", "#000000", "#ffffff", "⚪"]
];

// Wii Iconic Games (50 Masterpieces)
const rawWii = [
  ["Super Mario Galaxy", "Nintendo EAD Tokyo", 2007, ["Platform 3D"], ["Campi di Gravità Sferici", "Rosalina e gli Sfavillotti", "Orchestra Sinfonica"], "3a Persona", "La gravità reinventata: salti tra pianeti sferici accompagnati da una maestosa orchestra sinfonica.", "PEGI 3", "Super Mario", "#0a192f", "#ffd700", "⭐"],
  ["Super Mario Galaxy 2", "Nintendo EAD Tokyo", 2010, ["Platform 3D"], ["Yoshi", "Cometa Astronave", "Genio Puro di Level Design"], "3a Persona", "Yoshi si unisce alla corsa cosmica nel più denso e perfetto concentrato di idee platform mai concepito.", "PEGI 3", "Super Mario", "#002b4d", "#76ff03", "🦖"],
  ["The Legend of Zelda: Skyward Sword", "Nintendo EAD", 2011, ["Action Adventure"], ["Oltrenuvola", "Wii MotionPlus Scherma 1:1", "Origine della Spada Suprema"], "3a Persona", "Ogni fendente col telecomando Wii muove la spada con precisione millimetrica nei cieli di Oltrenuvola.", "PEGI 12", "The Legend of Zelda", "#004d40", "#00e5ff", "🗡️"],
  ["The Legend of Zelda: Twilight Princess (Wii)", "Nintendo EAD", 2006, ["Action Adventure"], ["Lancio Wii", "Puntatore Arco Mirino", "Crepuscolo"], "3a Persona", "Tira con l'arco puntando lo schermo e doma Epona scuotendo il telecomando Wii al lancio della console.", "PEGI 12", "The Legend of Zelda", "#1c2518", "#ffd54f", "🏹"],
  ["Xenoblade Chronicles", "Monolith Soft", 2010, ["GDR Open World"], ["Shulk e la Monado", "Giganti Bionis e Meconis", "Vedere il Futuro"], "3a Persona", "Due colossali divinità pietrificate nel mare infinito e una lama rossa capace di prevedere il futuro.", "PEGI 12", "Xenoblade", "#00204a", "#00e5ff", "⚔️"],
  ["Wii Sports", "Nintendo EAD", 2006, ["Sport con Sensori di Movimento"], ["Tennis Bowling Golf Boxe Baseball", "Mii Giocabili", "Fenomeno Mondiale"], "3a Persona", "Il fenomeno culturale che ha fatto giocare nonni e bambini insieme nei salotti di tutto il mondo.", "PEGI 3", "Wii Series", "#0099cc", "#76ff03", "🎾"],
  ["Wii Sports Resort", "Nintendo EAD", 2009, ["Sport MotionPlus"], ["Isola di Wuhu", "Scherma Volo Frisbee Wakeboard"], "3a Persona", "Scherma all'ultimo colpo e voli panoramici sui vulcani della paradisiaca isola di Wuhu.", "PEGI 3", "Wii Series", "#007799", "#ffca28", "🏝️"],
  ["Super Smash Bros. Brawl", "Sora Ltd. / Game Arts", 2008, ["Picchiaduro Platform"], ["Sonic e Snake Debutto", "Emissario del Subspazio", "Smash Finale"], "2D Side-Scroller", "L'Emissario del Subspazio unisce tutte le icone del videogioco per salvare il mondo dall'ombra.", "PEGI 12", "Super Smash Bros.", "#1a0033", "#ffd700", "💥"],
  ["Mario Kart Wii", "Nintendo EAD", 2008, ["Corse Kart"], ["Volante Wii Wheel", "Debutto delle Moto", "Online Mondiale"], "3a Persona", "Gare indiavolate a 12 piloti impugnando il volante bianco tra impennate in moto e mega-funghi.", "PEGI 3", "Mario Kart", "#b71c1c", "#ffeb3b", "🏎️"],
  ["Metroid Prime 3: Corruption", "Retro Studios", 2007, ["Action Adventure"], ["Mirino Libero con Puntatore", "Phazon e Corruzione"], "1a Persona", "Il miglior sistema di puntamento e sparo mai visto su console con libertà visiva totale.", "PEGI 12", "Metroid", "#002b1f", "#00e5ff", "🛸"],
  ["Metroid Prime: Trilogy", "Retro Studios", 2009, ["Collezione Action Adventure"], ["Tutti e 3 i Prime col Puntatore", "Edizione Steelbook"], "1a Persona", "Tutti e tre i capolavori di Samus Aran rigiocabili con la perfezione del telecomando Wii.", "PEGI 12", "Metroid", "#102027", "#ff9800", "🌌"],
  ["Donkey Kong Country Returns", "Retro Studios", 2010, ["Platform 2D"], ["Donkey e Diddy", "Isola di DK", "Livelli Sagoma Tramonto"], "2D Side-Scroller", "Retro Studios fa rinascere la saga di Rare con una sfida entusiasmante e carrelli minerari folli.", "PEGI 3", "Donkey Kong", "#e65100", "#ffd600", "🍌"],
  ["New Super Mario Bros. Wii", "Nintendo EAD", 2009, ["Platform 2D Multigiocatore"], ["4 Giocatori Contemporanei", "Mario Luigi e Toad", "Bolla di Salvataggio"], "2D Side-Scroller", "Quattro amici contemporaneamente sullo schermo tra salti sulla testa, risate e dispetti.", "PEGI 3", "Super Mario", "#d50000", "#76ff03", "🍄"],
  ["The Last Story", "Mistwalker", 2011, ["Action RPG"], ["Hironobu Sakaguchi", "Zael e Calista", "Città di Lazulis"], "3a Persona", "Il padre di Final Fantasy firma una toccante fiaba d'armi e magia con coperture tattiche.", "PEGI 16", "The Last Story", "#1a0d24", "#ffd700", "🏹"],
  ["Pandora's Tower", "Ganbarion", 2011, ["Action RPG"], ["Aeron ed Elena", "Tredici Torri", "Catena di Orichalcum"], "3a Persona", "Scala tredici torri colossali per strappare le carni dei boss e salvare Elena dalla mutazione bestiale.", "PEGI 12", "Pandora's Tower", "#3e0000", "#ff1744", "⛓️"],
  ["Monster Hunter Tri", "Capcom", 2009, ["Action RPG"], ["Battaglie Sottomarine", "Lagiacrus", "Villaggio di Moga"], "3a Persona", "Tuffati nelle profondità marine per cacciare il maestoso leviatano elettrico Lagiacrus.", "PEGI 16", "Monster Hunter", "#004d40", "#00e5ff", "🐉"],
  ["Sin & Punishment: Star Successor", "Treasure", 2009, ["Rail Shooter Acrobatico"], ["Isa e Kachi", "Puntamento Ultrarapido", "Furia di Proiettili"], "3a Persona", "La maestria balistica di Treasure esplode su schermo con schivate aeree e proiettili a specchio.", "PEGI 12", "Sin & Punishment", "#0d47a1", "#ff3d00", "🎯"],
  ["No More Heroes", "Grasshopper Manufacture", 2007, ["Action Hack and Slash"], ["Travis Touchdown", "Beam Katana", "Ricarica Agitando il Telecomando"], "3a Persona", "Travis Touchdown scala la classifica dei dieci assassini più letali di Santa Destroy.", "PEGI 18", "No More Heroes", "#212121", "#ff1744", "🗡️"],
  ["No More Heroes 2: Desperate Struggle", "Grasshopper Manufacture", 2010, ["Hack and Slash"], ["Doppia Beam Katana", "Minigiochi a 8-bit"], "3a Persona", "Cinquanta assassini da abbattere, doppia spada laser e geniali lavoretti in pixel art vintage.", "PEGI 18", "No More Heroes", "#1a0005", "#ff5722", "🩸"],
  ["Red Steel 2", "Ubisoft Paris", 2010, ["Action Western Samurai"], ["Katana e Revolver 1:1", "Deserto Cel-Shading", "MotionPlus Reale"], "1a Persona", "Affetta i predoni del deserto e svuota il tamburo della calibro 45 con fendenti fulminei.", "PEGI 16", "Red Steel", "#bf360c", "#ffca28", "🤠"],
  ["Sonic Colors", "Sonic Team", 2010, ["Platform 3D/2D"], ["Parco Giochi Intergalattico", "Poteri dei Wisp Colorati"], "3a Persona", "I Wisp alieni trasformano Sonic in trivella, raggio laser e cometa nel miglior Sonic moderno.", "PEGI 3", "Sonic", "#002171", "#00e5ff", "🦔"],
  ["Punch-Out!! (Wii)", "Next Level Games", 2009, ["Pugilato Puzzle"], ["Little Mac e Doc Louis", "Animazioni Spettacolari", "Balance Board"], "3a Persona", "Trova il punto debole dei pugili stravaganti del circuito mondiale a suon di montanti e ganci.", "PEGI 12", "Punch-Out", "#004d40", "#ffeb3b", "🥊"],
  ["WarioWare: Smooth Moves", "Intelligent Systems", 2006, ["Party Game"], ["Le Forme del Telecomando", "Follia Assoluta"], "3a Persona", "Impugna il controller come spada, proboscide, ombrello o bilanciere in microgiochi fulminei!", "PEGI 3", "WarioWare", "#ffd600", "#e91e63", "👃"],
  ["Kirby e la Stoffa dell'Eroe", "Good-Feel", 2010, ["Platform Artistico"], ["Mondo di Filo di Lana", "Bottoni e Cerniere", "Dolcezza Infinita"], "2D Side-Scroller", "Un capolavoro d'artigianato dove ogni elemento dello scenario è fatto di tessuto, filo e bottoni.", "PEGI 3", "Kirby", "#ad1457", "#f8bbd0", "🧶"],
  ["Kirby's Return to Dream Land", "HAL Laboratory", 2011, ["Platform Classico"], ["4 Giocatori con King Dedede e Meta Knight", "Super Abilità Giganti"], "2D Side-Scroller", "Spade colossali che tagliano intere colline in quattro giocatori insieme sullo stesso schermo.", "PEGI 3", "Kirby", "#ec407a", "#ffd54f", "🌟"],
  ["Silent Hill: Shattered Memories", "Climax Studios", 2009, ["Horror Psicologico"], ["Torcia con Telecomando Wii", "Profilo Psicologico", "Ghiaccio Invece della Ruggine"], "3a Persona", "Punta la luce della torcia nel buio di una Silent Hill congelata e rispondi ai test dello psichiatra.", "PEGI 16", "Silent Hill", "#0d1b2a", "#80d8ff", "🔦"],
  ["Resident Evil: The Umbrella Chronicles", "Capcom", 2007, ["Rail Shooter"], ["Caduta della Umbrella", "Chris e Jill", "Ricarica con Scatto"], "1a Persona", "Spara agli zombie delle prime storiche missioni con la mira a infrarossi del telecomando.", "PEGI 18", "Resident Evil", "#1b1b1b", "#ff1744", "🧟"],
  ["Resident Evil: The Darkside Chronicles", "Capcom", 2009, ["Rail Shooter"], ["Leon e Krauser in Sudamerica", "Telecamera Movimentata"], "1a Persona", "Le missioni inedite di Leon e Krauser prima dei fatti di Resident Evil 4 con grafica da urlo.", "PEGI 18", "Resident Evil", "#261c14", "#ff5722", "🎯"],
  ["Resident Evil 4: Wii Edition", "Capcom", 2007, ["Survival Horror Action"], ["Mira Perfetta col Puntatore", "Headshot Istantanei"], "3a Persona", "L'edizione più divertente e reattiva di Resident Evil 4 grazie alla mira laser a puntatore.", "PEGI 18", "Resident Evil", "#1a0000", "#d50000", "🔫"],
  ["Dead Space: Extraction", "Visceral Games", 2009, ["Rail Shooter Horror"], ["Stazione USG Ishimura", "Necromorfi", "Puntatore Fucile al Plasma"], "1a Persona", "La caduta della Ishimura vissuta in prima persona con smembramenti tattici al plasma.", "PEGI 18", "Dead Space", "#102027", "#00e676", "💀"],
  ["House of the Dead: Overkill", "Headstrong Games / SEGA", 2009, ["Rail Shooter Grindhouse"], ["Stile Cinema B-Movie Anni 70", "Agente Washington"], "1a Persona", "Pellicola rovinata, dialoghi sopra le righe e fiumi di zombie spappolati a colpi di doppietta.", "PEGI 18", "House of the Dead", "#3e2723", "#ff1744", "📽️"],
  ["Tatsunoko vs. Capcom: Ultimate All-Stars", "Capcom", 2008, ["Picchiaduro 2D"], ["Ken il Guerriero Ryu Casshern", "Baroque Cancel", "Mega-Robot"], "2D Side-Scroller", "Lo scontro leggendario tra i campioni Capcom e gli eroi degli anime classici Tatsunoko.", "PEGI 12", "Versus", "#002171", "#ffd600", "⚡"],
  ["Muramasa: The Demon Blade", "Vanillaware", 2009, ["Action RPG 2D"], ["Kisuke e Momohime", "108 Lame Maledette", "Pittura Tradizionale Ukiyo-e"], "2D Side-Scroller", "Un dipinto animato in movimento ispirato alle stampe giapponesi con scontri a fil di lama.", "PEGI 12", "Muramasa", "#1a0005", "#ff4081", "🗡️"],
  ["Okami (Wii)", "Ready at Dawn / Capcom", 2008, ["Action Adventure Poetico"], ["Lupo Amaterasu", "Pennello Celestiale col Puntatore"], "3a Persona", "Disegna cerchi di sole, fioriture e tagli netti direttamente sullo schermo col Pennello Celestiale.", "PEGI 12", "Okami", "#3e2723", "#ffca28", "🐺"],
  ["A Boy and His Blob", "WayForward", 2009, ["Puzzle Platformer"], ["Caramelle Gelatinose Mutaforma", "Tasto Abbraccio"], "2D Side-Scroller", "Nutri il tenero Blob con caramelle per trasformarlo in scale, paracadute e buchi neri.", "PEGI 3", "A Boy and His Blob", "#004d40", "#76ff03", "🍬"],
  ["Zack & Wiki: Quest for Barbaros' Treasure", "Capcom", 2007, ["Avventura Grafica Puzzle"], ["Usa gli Oggetti col Telecomando", "Nave Pirata Barbaros"], "3a Persona", "Ruota chiavi, suona campane e usa serpenti come tenaglie nei puzzle più brillanti di Capcom.", "PEGI 7", "Zack and Wiki", "#ff6f00", "#ffeb3b", "🏴‍☠️"],
  ["Wii Fit Plus", "Nintendo EAD", 2009, ["Fitness e Benessere"], ["Wii Balance Board", "Yoga e Aerobica"], "3a Persona", "La pedana bianca che ha pesato e fatto fare stretching e snowboard a milioni di famiglie.", "PEGI 3", "Wii Series", "#2e7d32", "#76ff03", "🧘"],
  ["Mario Strikers Charged Football", "Next Level Games", 2007, ["Calcio Brutale"], ["Mega-Tiri da 6 Gol", "Parate col Telecomando"], "Isometrica", "Campi elettrificati, bucce di banana giganti e il portiere che deve parare sei palloni al volo.", "PEGI 7", "Super Mario", "#d50000", "#76ff03", "⚽"],
  ["Mario Super Sluggers", "Namco Bandai", 2008, ["Baseball"], ["Batti Fuoricampo Muovendo le Braccia", "Campi a Tema"], "3a Persona", "Impugna il controller come una mazza da baseball e spedisci la palla fuori dallo stadio.", "PEGI 3", "Super Mario", "#0277bd", "#ffeb3b", "⚾"],
  ["Mario Sports Mix", "Square Enix", 2010, ["Sport Arcade"], ["Basket Volley Dodgeball Hockey", "Personaggi Final Fantasy"], "3a Persona", "Mario, Luigi, Moguri e Ninja si sfidano a basket e palla avvelenata in arene stravaganti.", "PEGI 3", "Super Mario", "#1565c0", "#ff9800", "🏐"],
  ["Mario Party 8", "Hudson Soft", 2007, ["Party Game"], ["Fiera del Carnevale", "Puntamento del Telecomando"], "Isometrica", "Il primo Mario Party su Wii ricco di minigiochi gestiti agitando o puntando il controller.", "PEGI 3", "Mario Party", "#c2185b", "#ffeb3b", "🎪"],
  ["Mario Party 9", "Nd Cube", 2012, ["Party Game"], ["Veicolo Comune per Tutti", "Battaglie Boss"], "Isometrica", "I quattro giocatori salgono tutti sullo stesso veicolo affrontando titanici boss di fine percorso.", "PEGI 3", "Mario Party", "#00838f", "#ffd54f", "🚙"],
  ["PokéPark Wii: La grande avventura di Pikachu", "Creatures Inc.", 2009, ["Action Adventure"], ["Pikachu Giocabile", "Attrazioni dei Pokémon"], "3a Persona", "Pikachu corre, gioca a rincorrersi ed esplora il parco tematico dei mostriciattoli tascabili.", "PEGI 3", "Pokemon", "#ffd600", "#00e5ff", "⚡"],
  ["PokéPark 2: Il mondo dei desideri", "Creatures Inc.", 2011, ["Action Adventure"], ["Snivy Tepig Oshawott", "Parco dei Desideri"], "3a Persona", "Alterna i Pokémon iniziali di Unima per risolvere enigmi e salvare i compagni ipnotizzati.", "PEGI 3", "Pokemon", "#2e7d32", "#ff5722", "🍃"],
  ["Excite Truck", "Monster Games", 2006, ["Corse Arcade"], ["Modifica del Terreno al Volo", "Salto sui Crinali"], "3a Persona", "Sterza inclinando il telecomando e fai decollare i monster truck rimodellando le colline.", "PEGI 3", "Excite", "#d84315", "#ffd600", "🛻"],
  ["Excitebots: Trick Racing", "Monster Games", 2009, ["Corse Strambe"], ["Robot Insetto e Animali", "Minigiochi a Piena Velocità"], "3a Persona", "Lancia torte in faccia, fai sandwich al volo e volteggia alle sbarre mentre sfrecci primo.", "PEGI 3", "Excite", "#e65100", "#76ff03", "🦗"],
  ["Epic Mickey", "Junction Point Studios", 2010, ["Platform Adventure"], ["Warren Spector", "Topolino e Oswald", "Pittura e Solvente"], "3a Persona", "Topolino ripara o cancella il mondo dimenticato dei cartoni con pittura magica e solvente.", "PEGI 7", "Disney", "#1a0033", "#00bcd4", "🖌️"],
  ["Sonic and the Secret Rings", "Sonic Team", 2007, ["Platform di Corsa"], ["Mille e Una Notte", "Sterzata Inclinando"], "3a Persona", "Sonic corre a perdifiato tra le pagine delle Mille e una Notte guidato dal telecomando.", "PEGI 7", "Sonic", "#c2185b", "#ffca28", "🧞"],
  ["Sonic and the Black Knight", "Sonic Team", 2009, ["Action con Spada"], ["Caliburn Spada Parlante", "Cavalieri della Tavola Rotonda"], "3a Persona", "Sonic impugna la spada parlante Caliburn per sfidare i cavalieri di Re Artù a duello.", "PEGI 12", "Sonic", "#002171", "#ffd700", "⚔️"],
  ["Final Fantasy Crystal Chronicles: The Crystal Bearers", "Square Enix", 2009, ["Action Adventure"], ["Layle e la Telecinesi", "Mondo Fantasy"], "3a Persona", "Afferra mostri e veicoli col potere gravitazionale in una frenetica avventura fantasy.", "PEGI 12", "Final Fantasy", "#00204a", "#80d8ff", "🔮"]
];

writeConsoleFile('src/data/consoles/gamecubeGames.ts', 'GAMECUBE_GAMES', mapGames(rawGamecube, 'GameCube'));
writeConsoleFile('src/data/consoles/wiiGames.ts', 'WII_GAMES', mapGames(rawWii, 'Wii'));
